### ISSUE TITLE
Content pages app breaks the back button/browser history

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1054]
**Package**
app-content-pages

**Feature or Issue Description**
Navigate to the new publications page, then use the back button or browser history to navigate back to a previous page. The window location changes but the browser still displays the publications page.
![Screenshot showing the publications page displayed but the location is /projects.](https://user-images.githubusercontent.com/59547/62112805-60852100-b2ab-11e9-91c6-745280965394.png)

**Comment by shaunanoordin** [comment]
## Investigation Update

This issue appears larger than just the app-content pages, and seems related to how different modules that share the `zooniverse.org` domain (i.e. the original PFE, app-content-pages, app-project, etc) _dont share the same JS router._

⚠️ This issue cannot be tested on individual modules (app-content-pages, etc) but can only be seen in the interaction/navigation between modules on an assembled website (i.e. zooniverse.org)

⚠️ Update: @rogerhutchings informed me that this may be an issue with **NextJS's Back button and/or routing** - this may be our next point to investigate.

### Testing

Tested on macOS 10 + Chrome 78, on the live version of zooniverse.org (PFE commit fbdc32f8e5170b0cc3f16af2377000bdffeb5f02, monorepo commit 8139b9f79f25ffc16caaf902f7974e54ce420c2d, I think)

Check: when navigating from the original PFE module to the app-content-pages module on zooniverse.org, does the 'Back' button work?
1. go to `https://www.zooniverse.org/projects` -> see Projects page. (**This is the original PFE module**)
2. search for Planet Hunters TESS and navigate to it -> see Planet Hunters TESS project page (`https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess`)
3. click on Get Started -> see the Classify page for Planet Hunters TESS (**this is the new app-project module in the monorepo**)
4. Press 'Back' button on web browser, or otherwise navigate back (e.g. Cmd+Left Arrow) to the previous page, try to navigate back to the Projects page
  - Expected: I should see the previous pages
  - Actual: I continue to see the TESS Classify page. The web browser location, however, shows that URL has changed as expected - it's just that the web page content remains the same.

Observation:  
- The problem seems to stem when using the browser's 'Back' button to navigate from a page rendered in `monorepo/app-project` to a page rendered in `Panoptes-Front-End`.
- The problem seems generalised to any monorepo-NextJS module, since the original report by @eatyourgreens indicates the issue was with `monorepo/app-content-pages`.

Hypothesis:
- NextJS's router "eats" the history of any PFE navigation events that precede it?

More tests forthcoming.

UPDATE: I think NextJS routing works fine if you're going back/forth between NextJS components, it's just incompatible with whatever PFE's using. I'll write up my analysis on this shortly.

**Comment by eatyourgreens** [comment]
When you go back from the Publications page to the Projects page, the browser should make a request for https://www.zooniverse.org/projects, which it gets from the window history, and load PFE.

**Comment by shaunanoordin** [comment]
## Investigation Update 2: The Quickening

Check: when navigating from the original PFE module to the `app-content-pages` module on zooniverse.org, does the 'Back' button work?
1. go to About page at `https://www.zooniverse.org/about` -> see About page (this is rendered in PFE)
2. click on 'Publications' link to go to `https://www.zooniverse.org/about/publications` -> see Publications page (this is rendered in `monorepo/app-content-pages`)
3. press the Back button on my web browser
  - expected: I should see the About page
  - actual: I still see the Publications page. The web browser's window location changes to show the correct URL, and interestingly enough, the _About navigation bar also tells me I'm supposedly on the 'About page'_) 

This confirms what Jim originally reported. Now to get interesting...

Check: when navigating between pages within the `app-content-pages` module on zooniverse.org, does the 'Back' button work?
1. go to Publications page at `https://www.zooniverse.org/about/publications` -> see Publications page
2. click on 'Our Team' link to go to `https://www.zooniverse.org/about/team` -> see Team page (this too is rendered in `monorepo/app-content-pages`)
3. press the Back button on my web browser
  - expected: I should see the Publications page
  - actual: 👍 

Check: when navigating between **different NextJS modules and PFE,** does the Back button work??
1. go to Planet Hunters TESS project page at `https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess` -> see TESS Project page (PFE)
2. click on 'Get Started' -> see TESS Classify page (monorepo/app-projects)
3. click on About -> see About page (PFE)
4. click on 'Publications' link -> see Publications page (monorepo/app-content-pages)
5. press Back
- expected: see About page
- actual: 👎 no change, still seeing Publications page
6. press Back:
- expected: see TESS classify page
- actual: 👍 YES! For some reason, this works!
7. press back:
- expected: see TESS project page
- actual: 👎 no change, still seeing TESS classify page

So yeah, this seems to confirm the idea - the NextJS router is "eating" the location history of previous PFE page visits.

> When you go back from the Publications page to the Projects page, the browser should make a request for https://www.zooniverse.org/projects, which it gets from the window history, and load PFE.

It _should,_ and I'm not entirely sure why it isn't. 😕

**Comment by eatyourgreens** [comment]
This may have been fixed by #1635 or even #1634.

**Comment by srallen** [comment]
Did some testing for this and I don't think this is fixed. I can replicate _sometimes_ the issue using the steps outlined in [this comment](https://github.com/zooniverse/front-end-monorepo/issues/1054#issuecomment-552457204) and [this one](https://github.com/zooniverse/front-end-monorepo/issues/1054#issuecomment-552465156). When I replicated it with the about pages, one of the times the routing breaks because this error is thrown in the console:

![Screen Shot 2020-05-27 at 2 55 26 PM](https://user-images.githubusercontent.com/5016731/83066240-5b5b4480-a02a-11ea-9306-7b33a0a5c95a.png)

I'm unsure what the problem may be with the project app and using the back button, if it is similarly an error being thrown is interrupting the navigation. However, I'm going to link the reports for that error in Sentry to this issue.

I'm not convinced it's the router in next.js by itself causing this problem given that we see it in both apps, even after routing changes and API update in the content-pages app.

**Comment by eatyourgreens** [comment]
I think this and #1377 are the same bug. The error is being thrown by the Next router, from the stack trace.

**Comment by eatyourgreens** [comment]
There’s an `onPopState` handler in the Next router, which would be fired by the back button. https://github.com/vercel/next.js/blob/b7e17e09e5e51a8e33b728a1ef14f11e7bf009db/packages/next/next-server/lib/router/router.ts#L258

It’s not clear to me why the content pages are loading the router, or how we can turn that off.

The project app would be more complicated, since that is set up as a single page app.

**Comment by eatyourgreens** [comment]
Going back from the PH-TESS home page to the Projects page, I'm seeing the same `indexOf` error, which is thrown by the `addBasePath` function in the Next router.
![Chrome dev tools showing the source code for line 14 of the Next router.](https://user-images.githubusercontent.com/59547/83122866-23a4d900-a0cc-11ea-9b43-153ee33585f9.png)

**Comment by srallen** [comment]
@eatyourgreens I think this is fixed as I haven't seen it in a while. Can you confirm and close?

**Comment by eatyourgreens** [comment]
I’ve just reproduced it on both the Publications page and a project home page. Going from PFE to NextJS breaks the back button.

**Comment by eatyourgreens** [comment]
Here’s another example. 
https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/about/research
Go to Classify, then click the back button. You can’t leave the Classify page and return to the About page.

**Comment by eatyourgreens** [comment]
I'm an idiot. This is more than likely caused by the fact that we reload the page when you follow any of these links, which breaks the Back button in the browser. eg. go from Talk here to the project home page, or Classify, and back again.
https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/talk
