### ISSUE TITLE
Zoo header: notifications aren't shown

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1093]
**Package**
lib-react-components (I think)

**Feature or Issue Description**
I have one unread notification at the moment. When I go to the content-pages app or to the PH TESS classify page, that notification is not shown at the top of the page.

![Zooniverse projects page showing one unread notification at the top of the page.](https://user-images.githubusercontent.com/59547/63441664-ae63f380-c429-11e9-8c33-9ca2baa12d87.png)

![Zooniverse publications page showing no new notifications at the top of the page.](https://user-images.githubusercontent.com/59547/63441686-b9b71f00-c429-11e9-926a-b59d14cedc72.png)

**Comment by srallen** [comment]
The header in the react components repo does support props to pass in a notification count, but the header itself shouldn't handle how to receive those messages since it's only a UI library. The apps need to be setup with the websocket connection and a store for it I think. This means a bit of duplication between the apps, though, so we might want to consider how to share that bit of code between them.

**Comment by eatyourgreens** [comment]
I don't think it's even a websocket, since I have to refresh the page to see my unread notifications in PFE. I think it's an API call on page load/change.

**Comment by srallen** [comment]
Yes, PFE currently isn't using the websockets for this, but it could be.

**Comment by eatyourgreens** [comment]
Sure, but I don't think the server side for that is set up at the moment.
