### ISSUE TITLE
Make project announcement component dismissible

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1176]
The project announcement component was added in #1177 as a static component. The design shows that it should be dismissible, and the original issue (#594) states it should be dismissible for the session.

What's the best way to implement this? My current thinking is that on dismissal, the UI store is updated and saves that preference to [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage). When the client bundle loads, it checks `sessionStorage` the dismissal preference and updates the UI. This means that we can't SSR it in a dismissed state, but that doesn't bother me too much.

If there are any better implementation ideas, shout out

**Comment by eatyourgreens** [comment]
Session cookie?

**Comment by srallen** [comment]
@beckyrother says that this should happen before the banner appears on the classify page (related: #1196)

**Comment by beckyrother** [comment]
Related question: should we allow research teams to prevent people from being able to dismiss? Feel like this is going to be a request, we should have a point of view about it. Right now I'm pretty neutral – I'd like to be able to dismiss the message because it's quite distracting; however, I can see the use case for research teams to make sure their message is seen.
