### ISSUE TITLE
Snapshot tests can fail if there are any leftover changes in compiled grommet theme

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#118]
**Package**

`lib-react-components`

**Feature or Issue Description**

When I was reviewing #105, I found that the snapshot tests were initially failing. I discovered that it was because I'd compiled a version of the grommet theme with some additional stuff for modals, and it was causing a mismatch between the tested component and snapshot. There was no _actual_ discrepancy, it was just some additional styles I'd added for modals, but enough to cause the test to fail.

Using the source of the grommet theme would solve this issue, and save a compilation step in a separate package, but without knowing more about how snapshots work at the moment I'm not sure if this is a good idea or not.

**Comment by srallen** [comment]
A slightly different issue that I also want to comment here: 

The snapshot files shouldn't end up in the library's compiled files, but they are because the repo is still using a simple npm script setup with the babel CLI. I'll have to see if there's a way to tell the babel CLI to exclude certain file types. If it can't, then we'll have to switch to a more robust webpack setup.

**Comment by srallen** [comment]
Just commenting here that I've resolved the file ignoring that needs to happen in the build step. The babel-cli has a param that can be used just for this. I commented here in case it was related to the original issue described, but appears it isn't.

**Comment by srallen** [comment]
mocha-snapshots is being removed in #220 for now. We may try a different library or they might update the package when we circle back to it.
