### ISSUE TITLE
[VSLCV] individual bar focus

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1243]
**Package** lib-classifier

The bars in the BarChartViewer should have some kind of individual bar focus/hover state that shows the individual value. The way the stats bar chart does this by showing the number inside the bar width probably isn't going to work for this because we don't have an idea what the values will be. Any number with more than two or three digits won't fix inside the bar width comfortably. 

**Describe the solution you'd like**

Probably some kind of tooltip and the library we're using, vx, has one: https://vx-demo.now.sh/static/docs/vx-tooltip.html

Unfortunately, they don't have a demo of it in the gallery.

**Describe alternatives you've considered**

Maybe @beckyrother has other ideas.

**Comment by beckyrother** [comment]
![image](https://user-images.githubusercontent.com/1392130/67334590-067dab80-f4e8-11e9-8d82-ccdb0bf4c319.png)

As an example I added a hover state on the stats page, since it should also go there as well. Dark theme tk. InVision link: https://projects.invisionapp.com/d/main#/console/12924056/389926412/preview

**Comment by srallen** [comment]
For screen readers, we can implement the read out as a list with each individual bar as a list item. This is described in this article: https://www.a11ywithlindsey.com/blog/accessibility-d3-bar-charts
