### ISSUE TITLE
Allow requests for aggregated data from Caesar

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1271]
If enabled, we should be able to request aggregated data - specifically transcription data for IMLS - from Caesar and make it available as a drop-down option in the text input subtask.

See Anti-Slavery Manuscripts for an example.

- [x] Requesting and storing data: we may be able to do an OPTION request to see if there's anything actually available
- [ ] ~UI to show the results to the volunteer (ASM uses a list of buttons styled like a dropdown).~ Documented in #1316 

Related ADR PR:

#1268

**Comment by rogerhutchings** [comment]
Time estimate: 1 person, 1 month

**Comment by eatyourgreens** [comment]
Here's the graphQL query to get previous annotations from Caesar:
https://github.com/zooniverse/anti-slavery-manuscripts/blob/af3c0acca8e66dadac87eb790b73cbc211f23563/src/ducks/previousAnnotations.js#L101-L134

Here's a function to parse the response for a given frame number:
https://github.com/zooniverse/anti-slavery-manuscripts/blob/af3c0acca8e66dadac87eb790b73cbc211f23563/src/ducks/previousAnnotations.js#L170-L195

and here are the helpers used by that parsing function:
https://github.com/zooniverse/anti-slavery-manuscripts/blob/master/src/lib/construct-previous-annotations.js

**Comment by eatyourgreens** [comment]
NB. the graphQL query requires a reducer key, which ASM has set in a config file. One key for staging and another for production.

**Comment by eatyourgreens** [comment]
Reducer keys are per workflow, but maybe we can dynamically generate the reducer key from the workflow ID? I suppose it would have to be manually created in Caesar, at the moment, but it could follow a pattern that's easy to generate in the classifier code.

**Comment by srallen** [comment]
Copying over some discussion and recommendations mentioned in Slack chat (https://zooniverse.slack.com/archives/CGP3K6X3P/p1581522106308100):

> A break down of the discussion around setting transcription keys in caesar.  After the call yesterday I realized I confused what service needed what key.  The monorepo needs to know the reducer key and ALICE needs to know the extractor key.

# What keys should caesar user for transcription tasks

## The case of collaborative transcription 

To build a panoptes front-end (monorepo) task that allows volunteers to work
collaboratively on transcriptions it needs to be able to pull in *reductions*
from caesar.  To ensure it pulls only the transcription reductions it will
need to know what key (on caesar) the transcription reducer is set up with.

## The case of ALICE

The ALICE text editor needs to be able to query caesar for the *extracts*
of transcription tasks in order to draw the original transcribed lines.
To ensure it pulls only the transcription reductions it will need to know
what key (on caesar) the transcription extractor is set up with.

## Option 1

A pre-determined key is used for both the transcription extracts and
reductions when the project is set up in caesar.

### Consequences

Any transcription project currently set up on caesar will need to have
a new extractor and reducer set up with the new key and be back filled.
Initially this would be Anti-Slavery Manuscripts (~3000 subjects), but
would likely also be Shakespeare's World.
Running the new reducer would not be much of an issue as no calls to
panoptes would need to be done, but running the new extractor would
require a full back fill.
Any project back filled like this will have duplicates in any caesar export
but if they are back filled the project will be using ALICE to create
future exports.
Setting up new project will require setting these keys correctly in caesar.

## Option 2

The key(s) are stored on the panoptes workflow object that the new transcription
task and ALICE can both read.

### Consequences

A new front-end element in the lab would need to be created to allow project
owners to enter this information. Current project set up on caesar will
still need to rerun the reductions (the reduction format has change slightly
for ALICE), but no back filling would need to be done.
Setting up a new project will require setting matching keys in both caesar
and in the lab.

## Proposal

Go with option 1 and use the key `alice` for both the extractor and reducer.
Scripts already exist for caesar back filling, and only 1-2 projects will need
it.

**Comment by srallen** [comment]
@eatyourgreens can this close with #1520 merged? I think so?

**Comment by eatyourgreens** [comment]
I think so too. I was leaving it open for the UI part, but that has its own issue.
