### ISSUE TITLE
Future changes to projects app

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#143]
This is a quick list of some requests from @hrspiers for a projects listing app (i.e. the `/projects` route)

- Project cards should include an institution name where relevant
- Ditch disciplines filter bar
- Drop pagination in favour of having all projects on one page
- Redesign filters similar to a travel app, with a collection of checkboxes
- Filters:
  - subject
  - discipline
  - time
  - difficulty
- Check sorts for any bugs
- Add explanatory blurb to top

**Comment by srallen** [comment]
I disagree with dropping pagination. Infinite scroll has a lot of accessibility issues: https://www.boia.org/blog/the-impact-of-infinite-scrolling-on-website-accessibility

It can also decrease click throughs for goal-oriented search: https://www.nngroup.com/articles/infinite-scrolling/
(tl;dr Infinite scroll typically works best for content that is meant to be passively consumed and streamed, i.e. twitter, facebook. It doesn't work for content that is meant for click through, like e-commerce sites. Etsy famously dropped infinite scroll to go back to pagination.)

Some of these issues can be worked around, but I'm not sure the benefits out weigh the potential costs here. Pagination is pretty easy to do and support.  Improving filtering and sorting with pagination I think would be a better use of our time. We could instead add an option to increase page size so that users can control the number of projects displayed at a time.

Redesigning this page is on @beckyrother's to do list, so she should be brought into the conversation.

**Comment by beckyrother** [comment]
Thanks @srallen! This page has a lot of potential for improving sorting, search, and overall usability. It's next on my list to take a look at, so please wait before making changes – don't want to end up doing double work.

**Comment by srallen** [comment]
@seanmiller26 just assigning this to you just to share some of the ideas about this in the past. It probably makes sense to note this somewhere and then close since we're likely not going to work on this any time soon.
