### ISSUE TITLE
Transcription Line icon

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1452]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
The transcription line tool is a text transcription specific variant of the line drawing tool. It has slightly different UX and and visual design to indicate the start and end of the lines. To this end, it should have a different icon to indicate its function. 

The icon is: https://github.com/zooniverse/front-end-monorepo/pull/1369#issuecomment-568001353

**Describe the solution you'd like**

The icon was attempted to be added in #1369 but it did not render correctly: https://github.com/zooniverse/front-end-monorepo/pull/1369#issuecomment-575513064

**Comment by eatyourgreens** [comment]
Here's the new icon:
![transcription tool icon](https://user-images.githubusercontent.com/1392130/71270766-00555100-2318-11ea-8ab7-0a889060fdd7.png)
[transcription.svg.zip](https://github.com/zooniverse/front-end-monorepo/files/3989307/transcription.svg.zip)

The SVG file looks fine to me but when I tried adding it to the drawing tools, it wouldn't render correctly: ![Transcription tools in the classifier, showing the SVG icon as a blob of colour instead of the letter A.](https://user-images.githubusercontent.com/59547/72593331-96bb6900-38fc-11ea-9937-19100aa908f4.png)

**Comment by srallen** [comment]
@beckyrother will be updating the icon.

**Comment by beckyrother** [comment]
[ic-text.svg.zip](https://github.com/zooniverse/front-end-monorepo/files/4452241/ic-text.svg.zip)

Please try this icon. I'd like to see it in use before I know for sure if this will match the rest of our icon suite.

**Comment by srallen** [comment]
@beckyrother here's how it looks:

<img width="387" alt="Screen Shot 2020-04-09 at 3 11 01 PM" src="https://user-images.githubusercontent.com/5016731/78936535-5e977280-7a74-11ea-905f-da904bbcf81b.png">

**Comment by beckyrother** [comment]
OHH it's an outline and not a fill! That changes everything. New icon incoming

**Comment by beckyrother** [comment]
Sorry for all the changes. Try this please?

[ic-text.svg.zip](https://github.com/zooniverse/front-end-monorepo/files/4458942/ic-text.svg.zip)

**Comment by srallen** [comment]
@beckyrother Here's how that one looks:

<img width="392" alt="Screen Shot 2020-04-13 at 10 43 08 AM" src="https://user-images.githubusercontent.com/5016731/79134676-b59e8f80-7d73-11ea-9c33-c2eb34683210.png">

**Comment by beckyrother** [comment]
YESS much better. Thank you!! Approved on my end.
