### ISSUE TITLE
Seemingly unbounded memory growth for server side next.js apps

### ISSUE THREAD

**Issue by camallen** [zooniverse/front-end-monorepo#1469]
**Package**
`app-project` and `app-content-pages`

**Describe the bug**
Memory growth of the apps starts at about ~80-90MB and continues to grow while the app is running. This seems to massively impact the app response times as well.

**To Reproduce**
Visit new relic page for the app in question to see RAM use of the different app/pods
OR 
use kubectl cmds to get the resource usage (note values in Mi not MB)
```
# app-content-pages
kubectl top pod -l app=zooniverse-org-content-pages-production
NAME                                                       CPU(cores)   MEMORY(bytes)   
zooniverse-org-content-pages-production-65c4748fd8-b9slp   1m           364Mi           
zooniverse-org-content-pages-production-65c4748fd8-qlx5d   6m           386Mi        
# app-project
 kubectl top pod -l app=zooniverse-org-project-production
NAME                                                 CPU(cores)   MEMORY(bytes)   
zooniverse-org-project-production-569c9df54d-257pw   423m         905Mi           
zooniverse-org-project-production-569c9df54d-xtdk5   395m         860Mi          
```

To get a better handle on the starting points of the app resource usage:
1. roll the current pods and get fresh ones into service
0. ensure the apps are working as expected
0. check their resource usage
0. revisit after longer periods (hours, days, week) to get values on the resource usage.

**Expected behavior**
Memory grown should not be unbounded, it should taper off to a gradual increase. 

An interesting article on memory leak hunting in node apps https://medium.com/@casperle13/hunting-memory-leaks-in-server-side-rendered-react-application-311c6306d552

**Screenshots**
Visit https://zooniverse.slack.com/archives/CANKLB50E/p1580211118093800 for more info

**Comment by srallen** [comment]
Thanks. The culprit of the incorrect use of styled-components described in the article is interesting because we've made the same mistake after doing a search against our own codebase; we have some nested template literals missing the `css` helper. This mistake is easily done because the SC docs don't really have a good description of the correct usage and why it's so important in SSR cases. An ongoing issue discussing this: https://github.com/styled-components/styled-components-website/issues/209 

They've posted an issue to add a warning about dynamically created components wrapped with `styled` which is another possible source of memory leaks that we need to search our codebase for too: 
https://github.com/styled-components/styled-components/issues/2913#issuecomment-571272307
https://github.com/styled-components/styled-components/pull/2998

This issue also describes memory leaks related to SC as well: https://github.com/styled-components/styled-components/issues/2979

**Comment by srallen** [comment]
I have a WIP local branch to start to add the `css` helper to bits of code that should have it.
