### ISSUE TITLE
MultiFrameViewer should gracefully handle non-image frames

### ISSUE THREAD

**Issue by simensta** [zooniverse/front-end-monorepo#1471]
Currently the multiFrameViewer is setup to handle subjects where all the frames are images. Eventually, the multiFrameViewer may need to handle non-image frames.

**Comment by goplayoutside3** [comment]
Since this Issue was created we've had a pattern of creating separate subject viewers for subjects with multiple types of data - for example the ImageAndTextViewer or DataImageViewer components.

Closing in favor of future Issues that document specific types of subject data and/or Zooniverse projects funded to build new subject viewers.
