### ISSUE TITLE
Local production builds of the content pages app give 500 errors

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1499]
**Package**
app-content-pages

**Describe the bug**
Building and running the content pages app with `docker-compose build` and `docker-compose up` from the root of the monorepo gives 500 errors. The actual error is this (for the publications page):
```
TypeError: publicationsData.map is not a function
```
The team page gives a similar error, but `teamData` not `publicationsData`.

Running the app with docker-compose from `packages/app-content-pages` is fine. I think the problem might be that the Contentful environment is undefined for the top-level Docker build.

**To Reproduce**
Run `docker-compose build` and `docker-compose up` (or `docker-compose up --build`) from the root of the monorepo. Browse to http://localhost.zooniverse.org:3001/about/publications once the NextJS apps start up.

**Expected behavior**
You should be able to browse the publications page at
http://localhost.zooniverse.org:3001/about/publications
and the team page at
http://localhost.zooniverse.org:3001/about/team

**Comment by eatyourgreens** [comment]
I'm going to re-open this. The server errors are fixed, but starting the apps locally shows an error message now, when it should show the page content.

**Comment by camallen** [comment]
Sounds like you need to re-build the base image to ensure it's copied the local `.env` file into the `production-apps` base bootstrap image. Jumping into the running container should allow you to see if that file is there or not.

**Comment by eatyourgreens** [comment]
I've rebuilt it several times 😞

**Comment by eatyourgreens** [comment]
If you're able to get it working locally, I'd love to know how.

**Comment by eatyourgreens** [comment]
This should be fixed by #1494.

**Comment by camallen** [comment]
I had a look at this last night. 

Perplexingly i got the same as you did. The root dockerfile / compose builds do not work even with the .env in the image. Strangely, even when i volume mounted local code into the container ran `yarn dev` the code reported compilation on the fly but still didn't work (compilation issues?). FWIW i even manually removed the precompiled next data `rm -rf .next/` to ensure it was fresh.

I then tried broken code mounted into the container and `yarn build` which failed to build (expected) but then `yarn dev` still worked just fine which was lost me and where i stopped. 

My initial assumption is the original dockerfile builds aren't working as expected, even with the .env present. However tests showed there is something else at play that i'm not grasping. 

```
# start the container via bash
docker run -v $(PWD)/package.json:/usr/src/packages/app-content-pages/package.json -v $(PWD)/src:/usr/src/packages/app-content-pages/src/ -p 3001:3000 -it --entrypoint bash front-end-monorepo_prod:latest

# i manually built images from bootstrap and production-apps targets but both exhibited same issues.

# remove the pre built next data
rm -rf .next/

# run yarn cmds
yarn build
yarn dev
yarn start
```

I can get it to work via the prod docker files in the `packages/app-content-pages` dir based on the dockerhub image, so that is a lead.

**Comment by eatyourgreens** [comment]
I'm going to open a PR that reverts many of the changes in #1109 and goes back to the much simpler build process that @rogerhutchings originally set up. Even if we don't merge it, it may point us in the direction of what's going wrong.

**Comment by eatyourgreens** [comment]
Something I haven't tested: run the content app from the root directory and see if it works.
```
yarn workspace @zooniverse/fe-content-pages build
yarn workspace @zooniverse/fe-content-pages start
```

Wild speculation: when it starts, it's looking for `.env` in the current working directory, not the package directory?

**Comment by eatyourgreens** [comment]
I've run the content pages app from the root directory of the monorepo and it picked up the environment just fine. So it's not the working directory that's the problem.
```
yarn workspace @zooniverse/fe-content-pages build && yarn workspace @zooniverse/fe-content-pages start
```

**Comment by eatyourgreens** [comment]
CI is running production builds now, without errors (#1944.)

Local Docker builds use `NODE_ENV=development`, but run without errors, so I'm going to close this.
