### ISSUE TITLE
Annotations from previous frames not saved with multi-frame subject

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1625]
**Package**
lib-classifier

**Describe the bug**
Only the most recent frame annotations persist, previous frame annotations overwritten.

**To Reproduce**
1. Go to http://localhost:8080/?project=3496&workflow=13983&env=production
2. Draw some points on one frame
3. Go to a different frame, draw some more points
4. Click done and only recent frame annotations saved, not initial points or go back to initial frame and won't see first points

**Expected behavior**
Annotations on every frame persists and saves to classification.

**Comment by mcbouslog** [comment]
I think current code is creating new InteractionLayer instance with each frame, when a single instance of the InteractionLayer should be part of MultiFrameViewer.

**Comment by mcbouslog** [comment]
I think #1538 might be related in a sense. Similar to scale, for a survey workflow would we expect drawing marks to persist across frames? Clearly for a transcription type workflow we would not want the transcription lines to persist from page to page. Though regardless of workflow type, the markings should save, as this issue states.

**Comment by eatyourgreens** [comment]
There's a workflow setting in the project builder, which toggles whether marks are unique to each frame or cloned across all frames. Solar Stormwatch is an example of a project where you make a different drawing on each frame, because they're interested in measuring changes.

Space Warps is an example of a project where your marks are shown across all frames. From what I remember, it causes problems with PFE's subtask popups. Maybe they only show up on the original mark, or maybe they open on all copies of a mark when you click just one? I don't remember.

Anyway, it might be worth toggling that option on/off in a test project, just to get an idea of how it works.

**Comment by srallen** [comment]
Closed by #1658
