### ISSUE TITLE
Classifier - (Simple) Dropdown Task - how to implement "Other" free-form text field

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1751]
## UI Feature Required

Package: `lib-classifier`
Related to: #1750
Project: Engaging Crowds

As part of the Engaging Crowds project, we're building a _simple_ Dropdown Task in the monorepo. (simple = non-cascading) As part of the DD Task's features, it has to have the option to allow users to type in free-form text.

Now, if we're designing the DD Task to follow classic/standard dropdown web element patterns - i.e. a `<select>` element - then how are we presenting that free-form text field? As of PR #1750, I'm taking cues from Google Forms...

<img width="652" alt="Screen Shot 2020-08-10 at 13 32 01" src="https://user-images.githubusercontent.com/13952701/89782870-ef0ebe00-db0d-11ea-8d1d-4e09f2ec029c.png">

_(i.e., a free-form `<input type="text>`pops up when you choose the "Other" answer)_

...but this will be worth tagging @beckyrother .

### Status

Nothing to worry about right now since #1750 is still working on the basic "dropdown" UI.

**Comment by srallen** [comment]
I don't think we've decided to support this. I'd like to get feedback first about usage, which @lcjohnso has basic stats on, before we do design and work toward it. See: https://github.com/zooniverse/front-end-monorepo/issues/1679#issuecomment-671396204

**Comment by beckyrother** [comment]
I'm hearing two different things. @snblickhan

**Comment by snblickhan** [comment]
Apologies for the confusion @beckyrother -- in our call this past week I was trying to clarify that when we talk about "Other" we're talking about it as an abstracted idea (e.g. a catch-all for "classification that isn't available on the dropdown list"), rather than an _actual item_ available in the menu. Hence my note about using the combo task to present a text entry field on the same screen, with some sort of instructional text noting that if the dropdown options were insufficient, a volunteer could type a novel entry into the text box. But the main point there is that it should be a separate task, not part of the simple dropdown. Does this help to clarify?

**Comment by goplayoutside3** [comment]
Removed in https://github.com/zooniverse/front-end-monorepo/pull/5382
