### ISSUE TITLE
Default modal heading styles have been removed

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1785]
**Package**
lib-classifier

**Describe the bug**
The default modal heading style is now grey text on a white background.

![Screenshot of the Add To Collections modal showing that the heading has lost its styling and now uses default text colours.](https://user-images.githubusercontent.com/59547/92134246-359bc380-ee01-11ea-9213-34a9025a5dcb.png)

**Expected behavior**
Default styling should be white text (`neutral-6`) on a teal background (`brand`).

**Additional context**
Default modal heading colours were changed to empty strings in #1683. Removing those defaults fixes the text and background colours, but doesn't seem to change the colour of the close button icon.
https://github.com/zooniverse/front-end-monorepo/blob/c8d588b82dd4bb5bcacf7154d02195fd7347d846/packages/lib-react-components/src/Modal/Modal.js#L24-L34

**Comment by srallen** [comment]
My thoughts on this were that the components in ZRC shouldn't assume that they're always going to be used with the default zooniverse theme, and in fact, apps like the new floating forests' map visualization don't. This is why the default was change by me to use an empty string because the app consumer should be setting which colors they want to use. The fact that this broke the add to collection modal was just an oversight on my part. FWIW, we could build it to assume `brand` and then expect someone to use a theme object that is the same, but I'm not sure.

**Comment by eatyourgreens** [comment]
Thanks for the explanation. That makes sense, but the Readme and the modal heading are still using the Zooniverse colours as defaults, which confused me.

>The fact that this broke the add to collection modal was just an oversight on my part.

I checked the following on PH-TESS and I think all of them are broken.
- login
- register
- tutorial
- field guide
- subject metadata
- add to collections

#1731 passes in the colours explicitly to a modal, but the close button icon doesn't pick up the text colour. There's a screenshot at the top of the PR where the text is off-white but the close button is grey.
