### ISSUE TITLE
Control panel overloaded with > 2 bands

### ISSUE THREAD

**Issue by adamamiller** [zooniverse/front-end-monorepo#1846]
**Package**

**Describe the bug**
Using the new interactive light curve viewer associated with Stellar Slueths, if we load > 2 filters for our light curves then the third filter overlaps the label (see the screen shot below). This makes it impossible to highlight/click on said 3rd filter. 

**To Reproduce**
Go to https://frontend.preview.zooniverse.org/projects/adamamiller/stellar-sleuths/classify - tab through until a light curve with 3 filters is presented.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/2434744/95636575-1a058780-0a55-11eb-8a11-35540e8f03ca.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Firefox v 80.0.1

**Comment by trouille** [comment]
@adamamiller Good that you posted this. Cliff, Sarah, and I were able to talk briefly about this today. 

Recommendation: Move ahead with the beta with existing functionality to test for data quality with 2 filters only. Also use the beta as an opportunity to upload a subset of your beta subjects twice, first with with g-band and r-band and again with g-band and i-band (for example), to see which set of 2 filters is most reliable/useful. 

The above recommendation is because adding a 3rd filter would be a new feature/functionality. To date we've been building with 2 filters in mind, and so it's not a simple/quick fix to add a third. Also, participants are already going to be parsing significant information and options. This is a logical feature to include in our future roadmap for interactive subject viewers, but when we do have the ability to show 3 filters, we may find that it's not used by participants (because it's already quite a complex interaction). 

All to say, recommendation is to first test out through this beta the data quality you get with 2 filters.

**Comment by adamamiller** [comment]
@mcoughlin For the beta test we are going to proceed with only 2 filters - can you remake subject sets as either g+r or g+i. 

For consistency I think this means we are going to want to set the symbols of individual filters in the json files as well. We can sort that out offline.

**Comment by adamamiller** [comment]
@srallen no problem - we will just go with the defaults for now!

**Comment by srallen** [comment]
I'm going to close this for now since the beta test will be with two bands. If the beta test shows that we really need to make the subject viewer render dynamic up to N bands, then we can reopen this.
