### ISSUE TITLE
Bar graph axes are not correct

### ISSUE THREAD

**Issue by adamamiller** [zooniverse/front-end-monorepo#1848]
**Package**

**Describe the bug**
The axes for the two bar graphs in the interactive light curve viewer are still not fixed with the correct limits. For the amplitude, the range on the axis is still being determine dynamically. We would like amplitude to be plotted on a fixed scale between 0 and 3. For the period we would like to show the "log Period" (I believe this is happening now, though it is still labeled as Period), but in that case we need a scale from -2.5 to 3 (a large number of our sources have periods < 1 day, so we need this range to go to negative numbers). 

**To Reproduce**
Go to https://frontend.preview.zooniverse.org/projects/adamamiller/stellar-sleuths/classify 
Classify a few different candidates. 
The bar graphs will be dynamic in each case.

**Expected behavior**
We expect bar graphs to have fixed axis limits along the y-axis.

**Screenshots**
![image](https://user-images.githubusercontent.com/2434744/95637514-82556880-0a57-11eb-8593-47008ad588d1.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Firefox v 80.0.1

**Comment by srallen** [comment]
@adamamiller ok, so I think two of these requests are easily resolved. The bar chart supports configuration for the x-axis labels, so what you see rendered is coming in from the subject JSON. If you'd like it labeled `log period` instead, then it should be an easy update to the subject JSON for the bar chart options. In addition, I recently added configuration support for the y-axis domain (I don't think I've had a chance to communicate this back yet), so this is also configurable if you wish to set the y-axis to be a fixed domain rather than dynamic. Here is a link to the readme with more information on these configuration options:

- Notes on the bar chart in context of the variable star subject data viewer: https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md#barcharts
- README on the bar chart options in general: https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/README.md

Now for linear scale vs log scale, the bar chart is defaulted to using a linear scale for the y-axis and this is not configurable at this time. I recall conversation that a linear scale was ok for this, but I may have misunderstood requirement differences between the amplitude and period bar charts. If the period bar chart needs to be a log scale, then I'll need to add configuration support for this as I think most use cases for a bar chart will be a linear scale. I would suggest you hold off on setting the configuration for the domain until I add support for the log scale as how d3 functions for the different scale times might be different for the domain parameters. I need to double check the docs for this first. Could you confirm that log scale is required for the period chart? Thanks!

**Comment by adamamiller** [comment]
@mcoughlin It seems like we can achieve the desired effect by adjusting the JSON slightly from what we have right now. 

Under `"barCharts"` for the `"period"` entry, we want to update `"chartOptions"` to now be: 

        "chartOptions": {
          "xAxisLabel": "log Period",
          "yAxisLabel": "",
          "yAxisDomain": [-2.5, 3]
        }

And for the `"amplitude"` entry, we want to update `"chartOptions"` to now be: 

        "chartOptions": {
          "xAxisLabel": "Amplitude",
          "yAxisLabel": "",
          "yAxisDomain": [0, 3]
        }

The only thing I'm uncertain about is the proper "type" for the `"yAxisDomain"` entry (i.e. should there be quotation marks or {} in the `yAxisDomain` entry.

@srallen We will be fine using a linear scale! The one thing that may need to change, but this isn't that difficult, is that the change in the period bar chart is now additive rather than multiplicative. Whereas we previously would chart period*2 if a user clicks on `PERIOD MULTIPLE` = 2, now we want to chart: 

log Period –  0.301  for `PERIOD MULTIPLE` = 0.5
log Period +  0.301  for `PERIOD MULTIPLE` = 2
log Period +  0.477  for `PERIOD MULTIPLE` = 3

Does this make sense and is it possible to implement?

**Comment by mcoughlin** [comment]
I have made this change in the code, and am happy to upload an updated set when requested.

**Comment by srallen** [comment]
@adamamiller that should be an easy change. I'll look into it today.

**Comment by srallen** [comment]
Oh, and the domain in the JSON is expecting an array, so does not need quotations.

**Comment by adamamiller** [comment]
@mcoughlin Can you upload the updated set? The period multiples won't track exactly as we expect, but it'd be good to see what the bar charts look like with the new limits

**Comment by srallen** [comment]
@adamamiller Should the calculation for the period bar chart use the absolute value of the original data still? What I have in code now:

```js
    barChartJSON.period.data.forEach((datum) => {
      const phasedDatum = Object.assign({}, datum, { value: Math.abs(datum.value) * periodMultiple })
      phasedBarChartJSON.period.data.push(phasedDatum)
    })
```

What I'm going to change it to:
```js
    const additiveDictionary = {
      '0.5': -0.301,
      1: 0,
      2: 0.301,
      3: 0.477
    }

    barChartJSON.period.data.forEach((datum) => {
      const phasedDatum = Object.assign({}, datum, { value: Math.abs(datum.value) + additiveDictionary[periodMultiple.toString()] })
      phasedBarChartJSON.period.data.push(phasedDatum)
    })
```

**Comment by adamamiller** [comment]
@srallen We do not want the absolute value in this case since we will take the log as part of the pre-processing. So anything with a period < 1 day should have a negative value in the new bar charts. So, I believe what we need is: 
`const phasedDatum = Object.assign({}, datum, { value: datum.value + additiveDictionary[periodMultiple.toString()] })`

Please let us know when this is implemented so we can switch over to the new subject set.
