### ISSUE TITLE
[VSLC] No option to talk about individual subjects

### ISSUE THREAD

**Issue by adamamiller** [zooniverse/front-end-monorepo#1860]
**Package**

VSLCV

**Is your feature request related to a problem? Please describe.**

Most Zooniverse projects have a "Done" or "Done and Talk" option, to automatically allow subjects to be ported to the talk portion of the project. I cannot find an option to "talk" about individual subjects.

**Describe the solution you'd like**
Having an option to connect subjects to the Talk boards would be useful.

**Describe alternatives you've considered**
I also like that the process is fairly streamlined for the project at the moment. So, adding a second click to complete a subject classification may not be beneficial overall. 
 
**Additional context**
It's possible there is a "switch" that needs to be toggled in the project builder that would add this functionality. If I missed that sorry.

**Comment by beckyrother** [comment]
This might be a bug – assigning to Sarah.

**Comment by srallen** [comment]
@adamamiller this is both a bug and a configuration that you can self-serve. We had intended to reverse the logic in the new classifier to default to not show classification summaries because as you've noted, the vast majority of projects want the summary hidden. This got missed, so it was defaulted to show summaries, but we haven't built a summary view yet and that's why the Done & Talk didn't display. I'm going to submit a bugfix to default this to hide summaries, but in the interim, you can also manually set this configuration on the workflow editor page in the project builder lab to get the Done and Done & Talk to display correctly. You might have scroll, it's right after the tutorial linking options.

**Comment by adamamiller** [comment]
@srallen thanks - I have now selected "Hide classification summaries" to enable the "Done & Talk" button within the workflow
