### ISSUE TITLE
Sub-Task Popup shows sub-task for most recent Drawing Mark, not currently selected Drawing Mark

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1951]
## Major Issue

- Expected: when I click on a Drawing Mark (with a sub-task) to select it, the sub-task popup should appear, and the popup should show the sub-task for that **selected Drawing Mark.**
- Actual: the sub-task popup appears, it shows the sub-task for the **newest Drawing Mark**

### Testing

- Go to [blicksams's Transcription Task Testing](https://localhost:8080/?project=11300&env=production) (or any Workflow with Drawing Tasks that have sub-tasks, really)
- click to create your first Text Transcription Line 1️⃣ .
  - The sub-task popup should appear, with an empty text box.
  - for the transcription text, type in "Apple" 🍎.
  - Close the sub-task popup.
- click to create your second Text Transcription Line 2️⃣ .
  - The sub-task popup should appear, with an empty text box.
  - for the transcription text, type in "Banana" 🍌 .
  - Close the sub-task popup.
- click on the first Transcription Line 1️⃣ again.
  - The sub-task popup should appear with some text.
    - Expected: the sub-task should show the text typed in for the first line 1️⃣ , which is "Apple". 🍎 
    - ❌ Actual: the sub-task shows the text typed for the second line 2️⃣ , which is "Banana". 🍌 
  - Type in some new text, such as "Avocado" 🥑 
  - Close the sub-task popup.
- Submit the classification and monitor the submitted data.
  - Expected: the classification should submit annotation data that looks like `["Avocado", "Banana"]`
  - Actual: the classification submits annotation data that looks like `["Apple", "Avocado"]`

Tested on localhost with macOS + Chrome (on normal and with touchscreen emulation) on [blicksams's Transcription Task Testing](https://localhost:8080/?project=11300&env=production), which features a text transcription task.

**Advanced Testing:**

- On a new Subject, create the first Text Transcription Line 1️⃣ 
- Create the second Text Transcription Line 2️⃣ 
- Delete the second Text Transcription Line 2️⃣ 
- Click on the first Text Transcription Line 1️⃣ 
  - Expected: the sub-task popup should appear with the first line's sub-task. 1️⃣ 
  - Actual: classifier crashes because it's trying to access the sub-task of a deleted Mark.

### History

This issue was discovered while testing PR #1950 . After additional tests, I discovered this problem exists as far back as commit dc114e3, so this problem doesn't seem to have been introduced by the refactor in #1922 / #1921 (which 1950 was a response to).

### Status

n/a, to be updated

**Comment by shaunanoordin** [comment]
Also someone help me: is it **sub-task** or **subtask?**

**Comment by eatyourgreens** [comment]
Thanks for the detailed report, @shaunanoordin. I've merged #1950 so that we can, at least, place transcription lines and investigate this.

The subtask form gets the active mark from the store context. Maybe there's an observer missing from `SubTaskPopup` here? It seems like the popup may not be reacting to changes in the `activeMark` prop. https://github.com/zooniverse/front-end-monorepo/blob/7c471f9e7e20815fecddf671d48807e03bb2ed03/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js#L19-L35

**Comment by eatyourgreens** [comment]
I've investigated a bit further, adding
```js
console.log(activeMark.annotations.toJSON())
```
to the container. That does show the correct annotation for the active mark, so the rendered value isn't matching the prop passed down from the container. The three lines here have the values 'one', 'two' and 'three', in order down the page. Clicking any line always shows 'three', as reported above.

![Screenshot of a transcription line with a value of 'Three' in the HTML, but the expected value of 'One' logged in the browser console.](https://user-images.githubusercontent.com/59547/102604475-245e9480-411c-11eb-93f4-8892e3a2c4cf.png)

**Comment by eatyourgreens** [comment]
I've found a problem. I removed `task.setAnnotation(annotation)`, in #1859 I think. When you have a single task in the model with multiple annotations, like we have here, that leaves the task annotation set to the most recent annotation that you created. The quick fix would be to put that back in to the code, I guess. I'll open a PR.

I'm not 100% sure why the text box isn't showing the annotation prop that was passed in. Did that cause bugs?

**Comment by eatyourgreens** [comment]
There might be a couple of different ways to tackle this:
- #1952 adds `task.setAnnotation(annotation)` back to the code.
- #1953 switches the text task to behave like other tasks, accepting an `annotation` prop which is updated on change.

#1952 might also be needed so that required tasks check their values against the correct annotation. We're only seeing this bug for transcription because it's triggered by editing an existing annotation for a given task. It doesn't show when you first create an annotation.

At the moment, on `master`, I think `task.setAnnotation(annotation)` only runs when you first create an annotation, so each task carries a reference to the most recent annotation, not the current annotation.

**Comment by eatyourgreens** [comment]
I forgot to add: you probably also need a task that creates multiple annotations in order to trigger this bug.
