### ISSUE TITLE
Previous marks block drawing in subsequent workflow steps

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#2003]
Issue is in first comment.

**Comment by eatyourgreens** [comment]
It turns out this is more serious than just a rendering bug. You can't draw on top of previous marks any more, because the `InteractionLayer` component is behind those marks.

To reproduce:
1. Load Worlds of Wonder: https://frontend.preview.zooniverse.org/projects/lbeiermann/worlds-of-wonder/classify/workflow/8871
2. Say Yes to the first question.
3. Mark a rectangle.
4. Try to add points to your rectangle during the second drawing task. It should be possible, but isn't.

I missed that in my initial bug report because you wouldn't draw on top of points, but you would on top of extended shapes.

Possible solution: style the `PreviousMarks` component with `pointer-events: none`?

**Comment by eatyourgreens** [comment]
This bug may also impact PRN projects.

**Comment by srallen** [comment]
@eatyourgreens could you clarify if #2002 and #2003 are describing the same bug then?

**Comment by eatyourgreens** [comment]
They are different bugs, as far as I can tell. I think this one is caused by pointer events being blocked from reaching the `DrawingCanvas` component in the interaction layer, because they are trapped by the previous marks layer now. Styling `PreviousMarks` to pass pointer events through to the underlying layer might fix it, assuming that doesn't interfere with transcription tasks.

**Comment by srallen** [comment]
The issue documented in https://github.com/zooniverse/front-end-monorepo/issues/2003#issuecomment-767470419 should have been documented separately as a styling issue still remains. I'll open another separate issue for the styling issue once my PR to fix what is being described in the comment is fixed.
