### ISSUE TITLE
Support light/dark setting on Light Curve Viewer

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#209]
**Package**

lib-classifier

**Feature or Issue Description**

We should support the light / dark mode on the scatter plot, which should be fairly trivial. @beckyrother may have thoughts on the colour palette for each?

**Comment by beckyrother** [comment]
@rogerhutchings can you post example screenshots?

**Comment by rogerhutchings** [comment]
At the moment it looks like this in both light and dark:

![fireshot capture 13 - react app setup - http___localhost_8080__project 1862](https://user-images.githubusercontent.com/2725841/47729585-5967ae80-dc58-11e8-9831-b2a85a7e6249.png)

**Comment by beckyrother** [comment]
@rogerhutchings Sorry for the delay. [Here's the graph](https://invis.io/UAN6AP0JTBC#/329807099_08-7_Dark_Graph) – it's a line graph rather than a scatter plot but should have the same idea. You should be able to `inspect` and see hex colors, but if not the data points are #ADDDE0, the background is #333333, and the (very optional) graph lines are #282828. [Here's also a second graph option](https://invis.io/UAN6AP0JTBC#/329807098_08-7-2_Dark_Graph_Opt2) if we needed to do a filled-in line graph for whatever reason. Let me know if anything else is missing!

**Comment by rogerhutchings** [comment]
thanks @beckyrother 👍
