### ISSUE TITLE
Transcription Task workflows do not work with additional tasks

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2102]
## To Reproduce
1. Go to the [Davy Notebooks Project lab page](https://www.zooniverse.org/lab/9006/workflows/18244) and activate Workflow #18244  
2. Then visit https://frontend.preview.zooniverse.org/projects/humphrydavy/davy-notebooks-project
3. Click on "Davy Notebooks Beta Test Workflow (2021)"
3. Respond to the Transcription Task prompts and click next
4. See error (does not move past Transcription Task screen to T2)

## Expected behavior
After the question task "Have all the volunteer-made underline marks turned grey?" the volunteer should click "Next" and be taken to the next Task in the workflow.

### Desktop (please complete the following information):
 - OS: Mac OS Catalina
 - Browser: Chrome
 - Version: 89

## Panoptes info
Project: 9006
Workflow: 18244

## Additional context
The team was hoping to go to beta on April 20, but I've told them we'd need to delay until April 27. Note that this bug may also be affecting any NEH institute teams using the Transcription Task (though I haven't had any additional bug reports other than the DNP team).

**Comment by eatyourgreens** [comment]
I think this might be caused by the changes in #2064. If the incoming workflow has `workflow.steps`, then `step.next` is expected to be defined on each step, except for branching steps.

**Comment by srallen** [comment]
> If the incoming workflow has workflow.steps, then step.next is expected to be defined on each step, except for branching steps.

This should not be the case. The order of steps is derived by the map order. This is why we're using map data structures to begin with. `step.next` is only defined if recursion is happening (see: https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-05.md#decision). If the code now is always expecting it to be defined, then we should reconsider this change because this was not the plan.
