### ISSUE TITLE
& text modifier should be a single character, not brackets

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2331]
For FEM transcription projects, the Text Modifiers menu includes an ampersand &.

This button currently creates bracketed modifiers: `[&][/&]`, which is not the expected behavior. It should generate a single character, `&`, without brackets. It's not a 'modifier' so to speak, but instead an option for volunteers to use in order to generate consistency for transcribing the `&` character (instead of `+` for example, which teams frequently see).

**Comment by shaunanoordin** [comment]
Acknowledging request, will update on dev plan soon!

**Comment by shaunanoordin** [comment]
Ahhah, I should have updated this with the dev plan. OK, so...

- There is a very quick hack that we can get out to add the "single" or "literal text tag insertion" right now. 
- By "right now", I mean look at PR #2384
- If the devs + science leads are happy with this, we need to clearly mark out the `&` tag as an exception to the rules that need to be addressed by a proper long-term change to the text modification system.
  - i.e. instead of just having every textTag inserted as `[textTag]...[/textTag]`, we also need _new categories_ of singleTextTags `[singleTextTag]` and literalTextTags `literalTextTag` with their unique insertion rules.
