### ISSUE TITLE
Feedback for single-answer-question "Unexpected Error"

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/front-end-monorepo#2353]
## Package

lib-classifier

## Describe the bug
Feedback for single-answer-question displays:
> An unexpected error has occurred.

on screen.

The feedback object in the classification metadata that is visible in the JavaScript console on Safari contains the expected values given the subject and the submitted answer. These are the subject specific values, not the workflow defaults, so at least some part of the feedback system seems to be working. 

The JavaScript console also displays:

> Aborting subject advance and showing feedback

## To Reproduce
1. Go to https://www.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters
2. Submit a classification on the "Feedback Tests" workflow
3. See error

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

Project 14770
Workflow 19357

## Expected behavior
A modal is displayed providing feedback to the volunteer about their last classification

### Desktop (please complete the following information):
 - OS: macOS Catalina (10.15.7)
 - Browser: Safari
 - Version: 14.1.1

### Smartphone (please complete the following information):

Not attempted

**Comment by mcbouslog** [comment]
@hughdickinson - apologies I should have responded with the following earlier - this issue is due to the FEM not implementing subject viewers (other than what's used with TESS) for the feedback modal yet.

I think PFE (I'm not sure if intentionally) doesn't show the subject viewer within the feedback modal for any task feedback that isn't for a drawing task per [these lines of code](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/features/feedback/classifier/helpers/open-feedback-modal.jsx#L70-L72). Additionally, the lab interface for drawing feedback includes a checkbox to not show/show the subject viewer, however this checkbox is not shown in the lab interface for the single choice task feedback (see point 2 below).

Do you want to show the subject viewer within the feedback modal for your task?

A few options forward include:

1. manually add `hideSubjectViewer: true` to your task feedback rule (I have a quick way of doing this, happy to take care of, please DM me on Slack if interested)
2. I'm working on adding the checkbox to hide the subject viewer within the feedback modal to all the lab feedback Edit modals
3. I'm working on adding the subject viewer to the FEM feedback modal

**Comment by hughdickinson** [comment]
Hi @mcbouslog. I don't think showing the subject along with the feedback is necessary for this task so option 1 is probably fine. I will message you on Slack as requested.

**Comment by hughdickinson** [comment]
Hi @mcbouslog. It seems like there are still some issues outstanding. In both Chrome and Safari, following the same steps as in the original issue, I now see a different error:
> Application error: a client-side exception has occurred (see the browser console for more information).

De-minifying the React error listed in the console gives:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.

**Comment by srallen** [comment]
@hughdickinson the fix hasn't been deployed to production yet. We'll let you know when it is. Thanks.

**Comment by mcbouslog** [comment]
You can check https://frontend.preview.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters/classify/workflow/19357?demo=true until we deploy to production, typically on Wednesdays mid-day (US Central).

**Comment by srallen** [comment]
@hughdickinson the deploy is all done. Do let us know if you come across any other feedback bugs.
