### ISSUE TITLE
Image display issues in tutorial

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/front-end-monorepo#2406]
The following image cropping, sizing, and resolution issues have been reported by our collaborators on the Engaging Crowds project:

![image](https://user-images.githubusercontent.com/5321335/132217730-bca79cca-fe1d-4587-9bdc-63547712a3c2.png)

![image](https://user-images.githubusercontent.com/5321335/132217784-8656f69f-674e-449d-a98f-2eb3b6541b81.png)

![image](https://user-images.githubusercontent.com/5321335/132218037-9bc45259-ce52-4e83-9024-707d35745268.png)

![image](https://user-images.githubusercontent.com/5321335/132218123-522a1364-8b3a-4ed5-a73b-859fc7d2e716.png)

![image](https://user-images.githubusercontent.com/5321335/132218163-e3c351ee-357f-4b2a-894d-ef99c8e9e971.png)

**Comment by srallen** [comment]
@mrniaboc could you actually link to the projects and workflows that are displaying these issues?

**Comment by trouille** [comment]
https://www.zooniverse.org/lab/12561/tutorial is one of them

**Comment by eatyourgreens** [comment]
Here's their project in the new frontend.
https://frontend.preview.zooniverse.org/projects/emhaston/the-rbge-herbarium-plants-collectors-and-discovery

My advice was to try to use landscape, rather than portrait, tutorial images. Some of their tutorial images are very tall. Scarlets & Blues might be an example that they can follow for images that work in the new tutorial.
https://www.zooniverse.org/projects/bogden/scarlets-and-blues

**Comment by shaunanoordin** [comment]
In regards to the **"main image" for each tutorial step,** I made a quick jaunt into the code, and here's what (I believe) is happening on the technical side:

In **PFE,** a Tutorial step's main image has a **set width** of 800px, and the **height is whatever.**
- Refs: [Tutorial uses MediaCard](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tutorial.jsx#L297-L302), and [MediaCard uses Thumbnail](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/media-card.jsx#L13) with width=800

In **FEM,** a Tutorial step's main image a **set height** of 200px, and the image follows the **"cover"** rule.
- The "cover" rule: _the image will fill the height and width of its box, once again maintaining its aspect ratio but often cropping the image in the process_ [(see here)](https://css-tricks.com/almanac/properties/o/object-fit/)
- Refs: [SlideTutorial uses Media](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js#L53-L59) with fit=cover and height=200

In theory it should be fairly easy to allow tall images, _on a technical level._ Whether this is what we want on a _design level_ is a different question.

Not covered in this quick investigation:
- Images embedded in the markdown (I'd need to look in the `<Markdownz>`)
- Long text getting squished in the markdown (probably CSS flex-related)
- Why images look pixelated when resized (if I'm to guess, it's because FEM first sends the image to our `thumbnail.zooniverse.org` (like PFE does), but then upscales it browser-side to follow the 'cover' rule (which PFE doesn't))

If this investigation needs to go on the priority list, let me know.

**Comment by lcjohnso** [comment]
@goplayoutside3 Is this issue resolved after Markdownz updates?

**Comment by goplayoutside3** [comment]
From Shaun's comment:
> - Images embedded in the markdown (I'd need to look in the <Markdownz>)
> - Long text getting squished in the markdown (probably CSS flex-related)
> - Why images look pixelated when resized (if I'm to guess, it's because FEM first sends the image to our thumbnail.zooniverse.org (like PFE does), but then upscales it browser-side to follow the 'cover' rule (which PFE doesn't))

- Images embedded in the markdown are fixed.
- Text does not get squished. 
- Not sure if pixelated images are still an issue.

Shaun's note that this is a design discussion is still true. SlideTutorial uses a Media component with fixed "width" and "cover" specifically for the main image of each tutorial step. Deciding to modify those two style parameters is a design decision. Do we want to continue controlling the styling as we have since FEM was launched, or do we want to change it to allow any image dimension in the tutorial step's main image?

https://github.com/zooniverse/front-end-monorepo/blob/024593972868e7a61505d28dc0f197582418f6a0/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js#L76-L82

**Comment by goplayoutside3** [comment]
@lcjohnso the question of whether we want to change the tutorial component to allow any image dimension in the tutorial step's "main" image was never decided. I think all live FEM projects have adjusted their "main" image for each tutorial step to work in a landscape orientation. Example:
![Screenshot 2024-01-04 at 2 42 53 PM](https://github.com/zooniverse/front-end-monorepo/assets/23665803/13bad3cd-beb4-4799-b625-fd0c9f049ab2)

Can I close this Issue for now?

**Comment by lcjohnso** [comment]
@goplayoutside3 OK to close.  Now that in-line images within the tutorial text are rendered correctly with Markdown syntax, that capability is an acceptable alternative to allowing for a portrait orientated "main image".
