### ISSUE TITLE
Use setInterval instead of setTimeout for oauth?

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#263]
**Package** lib-auth

**Feature or Issue Description**
ASM found that using timers was not always a reliable solution to determine if the bearer token has expired. If the client computer goes to sleep, the timer is paused. Instead, we could use `setInterval` to compare the current time to the expiration time and would begin again once the computer awakens. 

This is a suggested strategy in this SO flow specifically for dealing with token expiration: 
https://stackoverflow.com/questions/6346849/what-happens-to-settimeout-when-the-computer-goes-to-sleep/6347336

**Comment by eatyourgreens** [comment]
If the interval ends while the client has requests in progress, there might need to be a mechanism to wait for client requests to complete before invalidating the current token and setting a new one. Otherwise you could have a race condition where the auth client invalidates a token that's in use by a client request.

One way around that might be to clear intervals while requests are in progress, then set new intervals when requests complete? I think that ensures that intervals can only end while the client isn't busy, similar to how the PFE classification queue sets/clears timeouts while it's actually posting data.

PJC gets around this, for first-party auth at least, by prefixing all requests with a token check, and refresh if necessary. Thus, all requests are made with a valid auth header, but may have to wait for a token refresh to complete before the actual request is made.
https://github.com/zooniverse/panoptes-javascript-client/blob/50ab237d19d4f248a2e38c29a69fc93d28da1ba0/lib/api-client.js#L10-L13

ASM also uses the `beforeEveryRequest` hook to check token expiry before each API call. In that case, I think either pending requests are allowed to complete, or work in progress is saved to resend, before the browser is redirected to zooniverse.org in order to get a new token. PJC OAuth is complicated by the fact that third party apps can refresh tokens via an iframe, if the browser allows 3rd party cookies/data.

**Comment by srallen** [comment]
PJC can do this because it's coupled the auth client and the api client. We could certainly do that and maybe this is a case where we _should_ have some coupling. @rogerhutchings do you have any thoughts?

Another option would be to have the auth client load up some code, maybe in a service worker, that listens for the fetch event in the browser and then checks, renews or asks for renewal, and then adds the authorization header. This would keep the auth code still contained within that library and the api client could still accept an argument for the token if it's being consumed by an app or lib that is not using the auth client for some reason.

**Comment by eatyourgreens** [comment]
Is the token stored and managed by the API client? I can't remember, but if it is then the responsibility for checking periodically that the stored value is still valid should fall to the client too, which might make things easier. In that case, the auth lib's responsibility would be to get tokens from Panoptes as required by the API client, using the appropriate auth strategy.

**Comment by srallen** [comment]
I've purposely made the rewritten api client to be purely functional -- essentially just helper functions to set appropriate headers and do some validations written on top of superagent. I am of the opinion that it should not store or manage any state. The new auth client does store state: the bearer token, expiration, and user resource, so I think it should be the one managing the validation check. 

If there is any coupling with the api client, it would be just to call a function available from the auth client api before every request which would return the current token and set the authorization header. Alternatively, the auth client could listen to the fetch event and possibly add the header. Listening to the fetch event on the window doesn't couple to the api client since a consuming app could choose to not use the api client and instead use the window Fetch API or XMLHTTPRequest directly if it had reason to do so. Conversely someone could use the api client without the auth client and use their own code to pass in the token in as an argument to the request.

**Comment by eatyourgreens** [comment]
If the API client is getting the token from the auth client before each request, then that does seem like the logical place for the auth client to validate the token, and possibly refresh it, before giving it back to the API client. If it has expired, and can't be refreshed, I think it will need to ask the API client 'hey this token is about to expire, is there any work you need to do before I log the user out?' Otherwise, we potentially lose classifications in progress for people who've just put quite a bit of effort into them, which is the problem we ran into on ASM, AnnoTate and Shakespeare's World.

I'm not sure about the event listener. Would that just be listening to requests to Panoptes, or all requests being made by the page (Google Analytics, rollbar etc.)?

**Comment by srallen** [comment]
> I'm not sure about the event listener. Would that just be listening to requests to Panoptes, or all requests being made by the page (Google Analytics, rollbar etc.)? We want to be very sure about not leaking tokens to third parties.

I'm imagining something similar to what I wrote for the classification queue service worker:
https://github.com/zooniverse/front-end-monorepo/blob/e1b61057b2905c1d543eb9a06398fc48c58ad9db/packages/lib-classifier/src/workers/queue.js#L15-L35

The event listener would listen to all fetch events, but we would check against the request url to find out if we care about that specific request or not. What I'm not sure about is whether or not to do this actually in a service worker.

**Comment by eatyourgreens** [comment]
> The event listener would listen to all fetch events, but we would check against the request url to find out if we care about that specific request or not.

I guess CORS should prevent third-party code from exploiting this by making requests to the API, but broadcasting credentials like this does make me nervous.

Is the intention to cancel the request if the token is about to change, then retry it once a new token is obtained? I'm thinking of the race condition where a request begins at about the same time as the auth client refreshes the token, and Panoptes changes the current token before the request is received by the API servers. Ideally, auth'ed API requests should be deferred during the brief period that the auth client is changing state.

**Comment by srallen** [comment]
I'm not sure how the token would leak to third party doing this approach, but doing this in a service worker would be beneficial to security since they are sandboxed from the rest of the window object. 

Yeah, the intention would be to listen to the event, check if it's a request to Panoptes, then check the status of the token and refresh as needed, update the token on the request if necessary, then send it on its way. 

I'm also thinking about modifying the existing `getToken` API method call to check the status of the token before returning it and then make it the responsibility of the consuming app to modify their requests as needed.

**Comment by eatyourgreens** [comment]
>I'm also thinking about modifying the existing getToken API method call to check the status of the token before returning it and then make it the responsibility of the consuming app to modify their requests as needed.

I think that's what I had in mind: the consuming app sees auth as a black box that it can get valid tokens from. That way, the API client code shouldn't be coupled to the method that's actually used to generate valid tokens.

**Comment by srallen** [comment]
Yeah that might be how I do it in the end. I'm gonna experiment on a couple of different branches locally first. I'm a bit excited about service worker potential, though, so something to think about too.

**Comment by eatyourgreens** [comment]
Could this use a model where the consuming app subscribes to be notified by the worker when auth state changes, or am I over-engineering this? That might be equivalent to `auth.on('change', …)` in our older projects.

**Comment by srallen** [comment]
Closing as we've switch to use the current auth client and rethinking what we want to do for auth in the rebuild.
