### ISSUE TITLE
Navigating from classifier, to project home, back to classifier - task component not rendered

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2891]
## Package
- lib-classifier

## Describe the bug
Task area renders "Task component could not be rendered."

## To Reproduce
1. Go to [TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235) or [Beyond Borders](https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/classify/workflow/18383)
2. Click on project name to return to project home page
3. Click on project nav "Classify"

## Expected behavior
Classifier loads with tasks.

**Comment by goplayoutside3** [comment]
Did a little debugging on this. This only happens when navigating away from and back to the same workflow. On projects with multiple workflows, choosing a new workflow after navigating to the homepage will successfully load the Task Area.

The task components are showing an error because the SubjectStore does not have an `active` subject, and its `resources` and `queue` arrays are both empty.

https://github.com/zooniverse/front-end-monorepo/blob/620f53fdad6668a499aea9390bb0771c4a993078/packages/lib-classifier/src/components/Classifier/ClassifierContainer.js#L89

^^ After that line is called in the ClassifierContainer, the SubjectStore properties I mentioned are empty, and there's no follow up function called to fetch new subjects.

There was a significant refactor of this file in https://github.com/zooniverse/front-end-monorepo/pull/2793, so I'm going to tag @eatyourgreens here for visibility.

**Comment by eatyourgreens** [comment]
Thanks!  That's really useful. The classifier store is a global variable, defined in the `useStore` hook. So it isn't destroyed when the classifier unmounts. 

I thought resetting the queue would force a refresh from Panoptes, but obviously not. The subjects store doesn't work the way I thought it did.

**Comment by eatyourgreens** [comment]
I've got some changes to `useStore` in #2863, so I'll check whether this bug exists on that branch too.

**Comment by eatyourgreens** [comment]
Global variables can be tricky to debug, but this bug is triggering when the classifier is mounted with `store` already defined in the window.

**Comment by eatyourgreens** [comment]
For easier debugging, you can also trigger this bug by toggling 'Cache Panoptes Data' in the dev classifier, which avoids having to rebuild `classifier/dist/main.js` between changes.


https://user-images.githubusercontent.com/59547/155676290-afe6a42d-f25b-4e54-b51d-3985960f96e9.mov

**Comment by eatyourgreens** [comment]
Linking https://github.com/zooniverse/front-end-monorepo/pull/2141 for context. That's the PR where I added the global store.

**Comment by eatyourgreens** [comment]
#2895 should fix this. I'm not seeing it happen on I Fancy Cats, in the dev classifier, any more.

**Comment by eatyourgreens** [comment]
The bug was introduced by `if (!workflows.active?.prioritized)`, which applies the following block to every project that is *not* HMS NHS or Davy Notebooks. That's a warning to be wary of the logical NOT operator in new code.
