### ISSUE TITLE
Modal tutorial prompts before UPP can load to determine if tutorial should prompt

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2894]
## Package
- lib-classifier

## Describe the bug
Tutorial prompts before UPP and tutorial can load (or if signed out UPP won't load, but tutorial shouldn't prompt until know that signed out)

## To Reproduce
1. Sign in on https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess?demo=true
2. Go to classify
3. Will be prompted with modal tutorial, close tutorial
4. Go to Talk
5. Go back to Classify, will be prompted with modal tutorial

## Expected behavior
If signed in and close modal tutorial then modal tutorial won't prompt again

**Comment by goplayoutside3** [comment]
This bug is not fixed for all users. I'll document the difference I saw between user accounts. In each case, I visited [TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify)'s classify page, navigated to Talk, then back to its classify page.

I’ve dismissed TESS’s tutorial under my main user account a year ago, and that was saved in UPP so the tutorial does not reappear. However, in a newer account created about 2 weeks ago, when I dismiss TESS’s tutorial, it seems like that preference is not saved because the tutorial always reappears.

**Comment by eatyourgreens** [comment]
I think there’s a missing call to the `setSeenTime` action when Get Started is clicked. That’s the action that updates your preferences. 

It’s called from `setActiveTutorial` too, so I’m not sure why opening the tutorial doesn’t set the seen time.

**Comment by eatyourgreens** [comment]
I think calling `setSeenTime` here would fix it. 
https://github.com/zooniverse/front-end-monorepo/blob/cf5bc3338b71912c6534d92d2039f6c1477a583a/packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js#L38

**Comment by eatyourgreens** [comment]
Looking through the code, `tutorials.tutorialSeenTime` is set but never used, except in tests. That can be removed.

`tutorials.setSeenTime()` sets the time for a single tutorial, which is fine for a project with only one tutorial like PH-TESS, but `tutorial.setSeenTime()` for individual tutorials would be better on HMS NHS.

`setSeenTime()` updates UPP, which is where the seen time is stored, so it might also be better as an action on the UPP model.
