### ISSUE TITLE
Transcription Task: Subtask modal buttons do not work in mobile browser

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#3344]
## Package
lib-classifier
(maybe lib-react-components)

## Describe the bug
When completing a transcription task, the subtask modal has two buttons: "Save and Close" and "X" close button. When using a mobile browser, these buttons do not work as expected.

## To Reproduce

1. Use a mobile browser such as Safari or Brave
2. Visit any transcription project such as https://frontend.preview.zooniverse.org/projects/wgranger-test/anti-slavery-testing/classify/workflow/3392?env=staging
3. Click an existing transcription line to open the modal, and the modal buttons do not work
4. Create a new transcription line to open the modal, and the modal buttons do not work
5. See the same behavior in the Transcription Line story: https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/drawing-tools-transcription-line--subtask

## Expected behavior
The "Save and Close" and "X" buttons should close the modal or prompt the user if they want to continue without saving work.

## Screenshots
Modal buttons will not close this modal:
![modal](https://user-images.githubusercontent.com/23665803/175349346-4b9b95ec-46a6-48e6-8856-f8f640894d98.jpg)

### Smartphone (please complete the following information):
 - Device: iPhone 12
 - OS: 15
 - Browser: Safari or Brave
 - Version: latest

## Additional context
Maybe related to #3246

**Comment by eatyourgreens** [comment]
All the iOS browsers are WebKit, so this might be related to #3246.

**Comment by eatyourgreens** [comment]
The question task on [my test drawing workflow](https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3370?env=staging) is also broken on iOS, but the Save & Close button there does work in desktop Safari.

**Comment by shaunanoordin** [comment]
This might be a _semi-easy_ fix. 👌 

**Problem:**
- On the SubTaskPopup on mobile, clicking on the "Save & Close" button or the close (x) button doesn't close the popup.
- To be VERY specific:
  - everything in the _task area_ of the popup (below: areas within the red box) works normally.
  - everything _outside_ the task area (below: areas within the orange box) has their pointer actions **overridden**, replaced the "drag modal" action. (e.g. you can click & drag on the "save & close" button to reposition the popup)
<img width="283" alt="image" src="https://user-images.githubusercontent.com/13952701/182597258-4a2397a4-f9bb-4e2f-8786-82dc19224c19.png">

**Analysis**
- The SubTaskPopup component uses MovableModal which relies on "Rnd" from `react-rnd`
- By default, the `<Rnd>` component overrides all its children's pointer actions with the "drag modal" action.
  - But, the Rnd component has a `cancel` prop which allows us to specify (CSS class names for) child components that _shouldn't_ trigger the "drag modal" action.
  - Note: there's a difference in behaviour between mouse events and touch events though, so that why click-dragging on Save & Close on desktop allows you to BOTH click the button and drag the popup.
- In `<SubTaskPop>`, we deliberately gave the task area (marked in red, above) the `className="subtaskpopup-element-that-ignores-drag-actions"` property, which allows it to work properly, but the "Save & Close" button and close (x) button (within the orange area, above) don't have similar properties.

**Suggested Solution**
- In SubTaskPopup: wrap the Save & Close button in a Box with `className="subtaskpopup-element-that-ignores-drag-actions"`
- In MovableModal: ??? ❓ Not sure yet, I can't reach into React-Rnd to edit that close (x) button. I might either need to check for a newer version of the dependency which might already have a fix, or I might need to submit a PR fix to the dependency repo itself.

**Comment by eatyourgreens** [comment]
I think you can add a CSS class to the close button here:
https://github.com/zooniverse/front-end-monorepo/blob/f0e7b32757eff62cb93df95e9d19ec9fcc8c301b/packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js#L36-L41

**Comment by shaunanoordin** [comment]
I think this may be a good issue for our new intern Maysa, let me assign this to her over the course of this week or next. (Maysa, if you're reading this, hi! I probably asked you to look at this bug without informing you that the issue has already been written up and a solution has been found, awaiting implementation.)

**Comment by eatyourgreens** [comment]
I think moving `className="subtaskpopup-element-that-ignores-drag-actions"` from the task up to this containing `Box` will fix the 'Save & Close' button.
https://github.com/zooniverse/front-end-monorepo/blob/06c787901c105dfe719e8002ccef4af56a024eea/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js#L109

**Comment by shaunanoordin** [comment]
Please see Maysa's duplicate issue #3550 for additional video details on this matter.
