### ISSUE TITLE
UI: content Page: nav/header doesn't fill the viewport, aligns with main body.

### ISSUE THREAD

**Issue by MaysaB** [zooniverse/front-end-monorepo#3591]
## Package
app-content-page

## Describe the bug
The about/publications page has a header that doesn't span all the way across. This happens on both mobile and desktop(any time the window is reduced.
See screenshot:

https://user-images.githubusercontent.com/49612167/187881243-a2a7abaa-d283-4540-a4b0-817032f803e7.mov

## To Reproduce
1. Go to [Zooniverse Publications](https://www.zooniverse.org/about/publications) 
3. Click on dev tools and go to a mobile browser. Alternatively just make your screen smaller.
4. Scroll side to side.
5. See the white gap on the edge of the right hand side of the page.

## Expected behavior
The page should be responsive on all devices/screen sizes.

### Desktop (please complete the following information):
 - macOS 12.5
 - Chrome v.104. Firefox v.104.

### Smartphone (please complete the following information):
- iPhone 13 Pro Max, Safari, v.15.6

**Comment by eatyourgreens** [comment]
Here’s the same bug on the Team page (iPhone XS.)

![Team page on iPhone, showing that the navigation menu overflows the screen while the two column layout is squashed to the point that it’s difficult to read.](https://user-images.githubusercontent.com/59547/188204908-fbf4099f-ffd0-4156-8817-c296c2986fc0.jpeg)

**Comment by shaunanoordin** [comment]
This should be a pretty easy CSS fix, since we already have a solution pioneered by PFE. 👌

- Our `zooniverse.org/about/*` pages run a mix of PFE and FEM code.
- _About > **Team**_ and _About > **Publications**_ both run [FEM code](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/app-content-pages)
- _About > **(everything else)** all run [PFE code](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/pages/about)

If you look at a PFE About page, we can see how it handles narrow viewports:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/13952701/188580282-14c9df63-76e6-448a-a99c-112f87a07ecc.png">

We can transfer the solution to FEM's `app-content-pages`, and I think it's as simple as adding `flex-wrap: wrap` to the container `<nav>`. 

(EDIT/UPDATE: derp, OK, you'll probably need to add some extra stylings to get the padding looking right once it wraps.)

- Code to edit: [AboutHeader](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js)
- Some additional documentation you'd need: [Grommet's Box](https://v2.grommet.io/box) component (and specifically, how you'd specify flex-wrap the _Grommet way_ )
