### ISSUE TITLE
Settle on a bundling strategy for libraries and apps

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#36]
One of the side effects of creating multiple interlinked libs and apps using shared dependencies is that bundling has become a bit painful. We should settle on a common bundling strategy and toolset, especially given that webpack is doing non-spec-compliant

[Rollup](https://rollupjs.org/) might be a good way to go..

**Comment by srallen** [comment]
Commenting for reference (it's a year old): https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by srallen** [comment]
Size comparison for small libraries: https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953
tl;dr don't transpile if you don't need to.

**Comment by srallen** [comment]
Based on my reading so far, it seems like webpack and rollup are basically at the same point functionally. The advantage of rollup's spec compliance is only available if all of the library's or module's dependencies are also ES modules (https://github.com/rollup/rollup/wiki/ES6-modules) otherwise you have to compile to Common JS anyway. Rollup does have a feature where you can compile to both ES modules and Common js, but it uses a non-standard npm package.json feature by specifying the common js output to the package.json's `main` and the ES one to `module`. This is interesting, but doesn't seem worth the configuration time and the risk of using a non-standard NPM feature for something like panoptes.js. 

I think for now we should stick to webpack for apps and any libraries that need newer ES features, which mimics Common JS, and no compiling for simple libraries that don't need any new ES features, like panoptes.js. The team knows webpack, so there's the advantage of less time for other folks to get up to speed on contributing.

**Comment by srallen** [comment]
This is actually of interest to me possibly for use with the small libraries that need newer ES features: https://github.com/developit/microbundle

**Comment by rogerhutchings** [comment]
cc #597

**Comment by rogerhutchings** [comment]
Closing - we've removed transpilation where we could, Next.js uses webpack, and there's no drive to change the webpack setup for the classifier or shared components.
