### ISSUE TITLE
"document is not defined" on Maria Edgeworth Team page.

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#3673]
## Package
app-project

## Describe the bug
Loading the Maria Edgeworth Letters Team page displays a "document is not defined" error.

![The Maria Edgeworth Letters Team page showing a 'document is not defined' error.](https://user-images.githubusercontent.com/59547/190899723-4c0e4063-f3e1-467c-9997-f7637c41cab1.png)

## To Reproduce
1. Go to https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/about/team

## Expected behavior
The project team page should load.

**Comment by eatyourgreens** [comment]
Poets & Lovers is fine, so I'm updating this as specific to Maria Edgeworth Letters.

**Comment by eatyourgreens** [comment]
[Corresponding with Quakers](https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers/about/team) is also fine, so this must be specific to the Maria Edgeworth team. 

Adding an error boundary to the crashing page might help.

**Comment by snblickhan** [comment]
Confirming here that navigating to this page via About page tabs works fine, but it's breaking if you try to access via direct URL OR if using the back button (e.g. go to Team page, navigate to another tab in the About page, hit back). Mainly just adding here because it affects prioritization of the bug fix. 

Is it a photos thing, I wonder? They do have several images that they've uploaded to the Media tab and linked on the Team page (neither Poets & Lovers or Corresponding w Quakers has images on their Team page).

**Comment by eatyourgreens** [comment]
[The Davy Notebooks team](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/about/team) has photos but doesn’t crash. 

I think the Maria Edgeworth team might have accidentally discovered how to write Markdown that crashes our NextJS app in Node. Ideally, a page crash shouldn’t affect the project header or footer, so that you can still navigate away from a broken page.

**Comment by eatyourgreens** [comment]
The Maria Edgeworth team page loads fine when [parsed with `markdown-it`](https://master.pfe-preview.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/about/team) so the problem here could be a bug in our very old version of Remark.
