### ISSUE TITLE
Survey task choice scrolls to bottom of choice component on initial render

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3687]
## Package
- lib-classifier

## Describe the bug
With a survey task, after selecting a choice, the browser scrolls to the bottom of the Choice component.

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify/workflow/2434?env=staging
2. Click on any choice, i.e. Aardvark
3. See browser scroll to bottom of Choice component

## Expected behavior
The browser doesn't scroll after selecting a choice in a survey task.

**Comment by eatyourgreens** [comment]
Works without any problems on my phone (iOS 15.6.1.) I picked Honey Badger.

**Comment by eatyourgreens** [comment]
In desktop Firefox 104 (MacOS), choosing either Aardvark or Honey Badge scrolls the window down because the first question answer uses autofocus. That's an accessibility issue already covered by #2455. My suggestion would be to shift focus to the top of the Choice box when it opens. See Marcy Sutton's user testing of [accessible client-side page navigation](https://marcysutton.com/prototype-testing-accessible-clientside-routing/).

**Comment by eatyourgreens** [comment]
Looking at Snapshot Wisconsin, it looks like the image slideshow is focused when a choice opens, so you could focus the image at the top, with `tabindex=-1`, when the choice opens. You'll have to make sure that those images have alt text too. That's a bug that was reported by blind volunteers for survey tasks in PFE, using audio subjects.
