### ISSUE TITLE
Admin Mode: admin page link is not correct

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#3739]
## Package
app-project

## Describe the bug
The admin link target URL is incorrect.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess
2. Turn-on Admin Mode
3. Click "Admin Page" in nav header
4. Arrive at https://www.zooniverse.org/projects/admin/project_status/nora-dot-eisner/planet-hunters-tess and "page not found"

## Expected behavior
Click "Admin Page" in nav header and arrive at https://www.zooniverse.org/admin/project_status/nora-dot-eisner/planet-hunters-tess

cc: @eatyourgreens

**Comment by eatyourgreens** [comment]
The NextJS app is hosted at https://www.zooniverse.org/projects/, so that URL will be automatically used as the root for all of the project navigation links. I forgot that when I added the admin link. The simplest fix is probably to change that link to use the fully qualified URL of the project admin page.

**Comment by eatyourgreens** [comment]
May as well add this to #3736 since I've been rewriting the project header in order to test it with React Testing Library.
