### ISSUE TITLE
Placeholder images aren't loading in dev env

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#4294]
## Package
app-project

## Describe the bug
Placeholder images for components like TeamMember and RecentSubjects do not load simple-avatar.png and subject-placeholder.png when app-project is run in a dev environment.

## To Reproduce
Check out the latest in FEM on your local machine. Run `yarn bootstrap` then either `yarn dev ` or `yarn start`.

Vist a project's About > Team page such as https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/about/team

## Expected behavior
Assets in the /public folder of app-project or app-content-pages should load in a browser in a dev environment and on production.

Discovered during review of https://github.com/zooniverse/front-end-monorepo/pull/4292

**Comment by eatyourgreens** [comment]
If those components are using `next/image`, they should pick up the app `basePath`. If not, then that might be the problem.

**Comment by eatyourgreens** [comment]
Placeholders are broken in a production build too. Here’s the Recent Classifications box on the Classify page showing a broken image.

https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235

![Screenshot of the Recent Classifications box showing a broken image icon rather than a placeholder for an empty subject.](https://user-images.githubusercontent.com/59547/222098929-0b56fae6-893f-47b9-9900-2f73cefde3f1.jpeg)

**Comment by goplayoutside3** [comment]
Both components use Next.js [publicRuntimeConfig](https://nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration) which is now deprecated.

**Comment by eatyourgreens** [comment]
Placeholder images are still broken in production too. ☹️

**Comment by eatyourgreens** [comment]
Next.js static assets are also broken if you bypass the nginx proxy. Maybe the problem is a combination of `next/image` and Next.js middleware?

https://fe-project.zooniverse.org/projects/_next/image?url=%2Fassets%2Fsubject-placeholder.png&w=1080&q=75
