### ISSUE TITLE
Set up automatic deployment and npm publishing for ZRC

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#46]
[Zooniverse-React-Components](https://github.com/zooniverse/Zooniverse-React-Components) has already been imported, but we're currently maintaining two copies. We should get the monorepo set up on Jenkins to build and deploy our packages before too much time gets sunk into both.

@astopy, what can I do to get this set up?

**Comment by astopy** [comment]
You should just need to add a Jenkinsfile to the repo and Jenkins will find it automatically.

The Jenkinsfile in [aggregation-for-caesar](https://github.com/zooniverse/aggregation-for-caesar/blob/master/Jenkinsfile) is the best example to start from. That'll get you as far as building/pushing an image to Docker Hub. 

Then, rather than the "Deploy to Swarm" stage you'll want to add a stage that looks something like this:

```groovy
    stage('Deploy') {
        newImage.inside() {
            sh 'npm run-script deploy'
        }
    }
```

**Comment by srallen** [comment]
@rogerhutchings I'm a little confused about the comment here about ZRC already having been imported. It still seems that that needs to happen.

With the mono repo conventions, I was thinking that might be cleaner to have a new npm package in this repo since it'll have to be renamed to `@zooniverse/lib-zooniverse-react-components`. Then move over or rewrite individual components as needed. Do you have any preference?

**Comment by rogerhutchings** [comment]
We've created a new package for shared components.
