### ISSUE TITLE
How to handle TESS data subjects?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#48]
I've just had a talk with @eatyourgreens about how we handle data subjects for TESS, and wanted to jot down my thoughts:

## Assumptions

- Planet Hunters subjects will either be CSV or JSON, rendering a light curve graph
- It'll need a similar marking tool to the [current Planet Hunters](https://www.planethunters.org), i.e. a horizontal range marking tool (which could be used by other projects)
- The graph output is going to be specific to Planet Hunters
- We want to avoid project-specific code in the Classifier at all costs

## Ideas (in increasing order of complexity)

1. Pre-process the data subjects to produce SVGs, which are handled by the `SingleImageViewer`
1. Have the subject location point to a microservice function which produces an SVG image, and pass in the location of the data file as a parameter to that
1. Set a property on the workflow called `custom_subject_viewer`, which is a URL pointing to a JS bundle. This returns a React component for this specific project which renders a viewer capable of handling these subjects. The [subject viewer selection code in the classifier](https://github.com/zooniverse/front-end-monorepo/blob/start-classifier/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getSubjectViewer.js) would check for this property first, and load in the custom subject viewer if present.

## Questions

- Is the graph output _really_ going to be specific to this project? If not, we create **a generalised scatter plot subject viewer**.
- @eatyourgreens mentioned folding the graph data - if this is a requirement, we'll definitely need a custom subject viewer of some kind, which would rule out idea 3. If there's no other custom project code required, we could add this in to a generalised scatter plot renderer.

cc @srallen @shaunanoordin @chrislintott

**Comment by eatyourgreens** [comment]
Number 3 is probably ruled out by displaying the subjects in Talk, which doesn't have workflows.

I like the idea of preprocessing the light curves as SVG paths, then serving those as SVG images.

**Comment by eatyourgreens** [comment]
Folding the data: we probably don't need to do that until we've got aggregated results coming back from Caesar (to give us a period) so maybe shift the responsibility for that into a component which is responsible for rendering the Caesar feed?

**Comment by srallen** [comment]
The caveat with generating a SVG plot to mark on is that there must be metadata included with the subject so that the SVG mark can be calculated to relate it back to the original plot data. We did this with Intro 2 Astro's Hubble Law project: https://www.zooniverse.org/projects/zooniverse/intro2astro-hubbles-law/classify. It includes the metadata we need to make the calculation to relate the SVG coordinates back to the plot and then also calculate Hubble's Law for the student investigation activity. This is done by a FAAS called by caesar post-classification. 

This is probably fine for projects that have a simple marking task, assuming we have some sort of generalized code for pre-processing subjects with that included metadata and have a post-processing task which makes the mark usable for analysis. However, we do have a feature request to be able to change axis scale (or "zoom"), which is what Planet Hunter does now, as a minimum requirement for some projects. I believe this is a requirement for the TESS data/light curve viewer. 

I spoke to @trouille yesterday about this and suggested we make a Planet Hunters data viewer as a first pass for the upcoming requirements for the light curve subject viewer for the TESS data, which likely may be custom just to that project, but having a simple plot viewer will be desirable for many projects. 

I like the idea of a FAAS service that generates a SVG which could be used for an image viewer subject preview in collections and talk. 

Regardless of this project's requirements, having a `custom_subject_viewer` property is a good idea I think on workflows. I think the classifier library could also have a subject viewer prop that would accept a react component or html node too for customizations that bypasses the selection code for CFEs.

**Comment by eatyourgreens** [comment]
>I think the classifier library could also have a subject viewer prop that would accept a react component or html node too for customizations that bypasses the selection code for CFEs.

Minor point about code design, but I find passing components as children a lot easier to read and understand than passing them around as props.

**Comment by srallen** [comment]
I think we can close this. TESS light curve viewer is custom to that project using vanilla D3 in React. We may later abstract it to a general scatter plot viewer.
