### ISSUE TITLE
Metadata modal spacing is too large

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#4807]
## Problem
The metadata modal lists pairs of keys and values for the current subject, however this list includes lots of vertical space between entries.  This layout is very inefficient and leads to an increased need for scrolling.

![Screen Shot 2023-06-13 at 12 17 56 PM](https://github.com/zooniverse/front-end-monorepo/assets/2006101/c87034a6-d903-4665-a687-da63189c4a81)

## Describe the solution you'd like
Reduce the vertical spacing between metadata entries in the pop-up modal.

cc: @seanmiller26

**Comment by seanmiller26** [comment]
@lcjohnso good catch. I mocked this up with each line following our 30px spacing and it looks much better. We need to make sure all modals will follow these same rules. 

<img width="726" alt="Modal w Annotation" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/f8290749-5273-46a3-a958-c8677a5c97d5">

While we are touching this up I put together this simplified modal which has the sub-header removed, as I'm not sure it conveys anything important. Thoughts?

<img width="678" alt="Modal simplified" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/7f6abc43-0e56-4097-bc4d-ca790b364852">

**Comment by lcjohnso** [comment]
I agree 30px spacing is much improved, and I'm OK with dropping label/value headers.

**Comment by goplayoutside3** [comment]
I think the label/value headers were intended to be interactable. You can click on them to sort the table by alphabetizing either column. @seanmiller26  do you still want to remove them? ([Component story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/meta-tools-metadatamodal--default))

<img width="453" alt="Screenshot 2023-06-20 at 10 43 13 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/d625c4f7-e194-4a82-a3be-f9a8220052b1">

**Comment by lcjohnso** [comment]
Huh! I didn't realize sorting was possible on those columns.  Due to "hidden"-ness of feature, not sure how many people are using it, but seems like it _could_ be useful in some cases.

My recommendation: leave column titles and sorting ability for now. The presence of the titles aren't a significant negative, and the possibility of sorting is a possible positive that pushes me to want to keep them.

**Comment by goplayoutside3** [comment]
Sounds good, would it help to always have a caret (arrow) next to the column labels to show sorting?

**Comment by seanmiller26** [comment]
How are the values displays as of now? The order the project team entered them or alphabetical?

**Comment by lcjohnso** [comment]
Yes, the default ordering should be the order that the fields are uploaded.  Often that will be the best sort (i.e., let the teams set the ordering), and alphabetical won't necessarily be the most helpful.

**Comment by goplayoutside3** [comment]
Re: caret question - The more I looked at the modal, I realized it's not an easy fix to always display a caret. As mentioned, the metadata rows load in order of fields upload. It wouldn't make sense to display a caret because a "down caret" conveys an alphabetical sort and an "up caret" conveys the reverse. The column labels are focusable and show the "click" mouse cursor on hover, so is it alright to leave the label styling as is?

I opened a PR to reduce the row spacing to 30px.

**Comment by eatyourgreens** [comment]
Peter Mason figured out the default metadata order once. It’s the length of the label string, including whitespace, from shortest to longest. He used to advise project teams to pad labels with extra spaces in order to control the order of the subject metadata in Rails. 

The order in the original manifest makes no difference, IIRC, but this might all have changed since we upgraded Rails.

**Comment by lcjohnso** [comment]
As discussed during today's FE standup: I will follow-up with backend team to determine whether / how metadata labels are or can be ordered, and #4876 will resolve the primary part of the issue regarding display spacing.
