### ISSUE TITLE
Work out why delay test is breaking the Travis build

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#491]
**Package**

lib-react-components

**Feature or Issue Description**

While working on #487, in `packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js`, I had to skip a test as it breaks the Travis build. It runs fine locally, but on Travis it times out.

This is the failing test: https://github.com/zooniverse/front-end-monorepo/blob/4191d43775f75b7b21912d20c883b24e79a67620/packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js#L45-L55

**Comment by eatyourgreens** [comment]
This suggests trying `done()`. https://stackoverflow.com/questions/32730169/how-can-i-use-settimeout-functions-within-mocha-test-cases

**Comment by eatyourgreens** [comment]
Adding `done()` to that test fixes the test runner for me, but the test is just broken. It doesn't render an `Image` component so fails with.
```
1) Image
       should delay loading the image the given time in props.delay:

      Uncaught AssertionError: expected {} to have a length of 0 but got 1
      + expected - actual

      -1
      +0
      
      at Timeout.lengthOf [as _onTimeout] (src/Media/components/ThumbnailImage/ThumbnailImage.spec.js:53:49)
```

I think it's only passing at the moment because async tests without `done` are evergreen. See https://wietse.loves.engineering/testing-promises-with-mocha-90df8b7d2e35
