### ISSUE TITLE
Bring ZRC repo into monorepo

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#5]
Move the https://github.com/zooniverse/Zooniverse-React-Components repo into the monorepo

(side note, lerna has an `add` command which takes care of git history and such)

**Comment by srallen** [comment]
I left a comment in #46 about how to move the ZRC repo, but it's more appropriate her:

> With the mono repo conventions, I was thinking that might be cleaner to have a new npm package in this repo since it'll have to be renamed to @zooniverse/lib-zooniverse-react-components. Then move over or rewrite individual components as needed. Do you have any preference?

> ETA: once the repo is setup here, I'll update the readme in the old ZRC repo saying it's deprecated.

@mcbouslog has some time this week and could get it setup. I just read up on the `add` command and that seems to take care of the concerns I had.

**Comment by mcbouslog** [comment]
If I add the ZRC repo via `lerna add zooniverse-react-components --scope=app-project` the current completely separate ZRC repo (where we'll update/add things going forward) will continue to live on as is?

Or maybe I want to use `lerna import ../Zooniverse-React-Components` then rename in-line with other monorepo lib packages?

**Comment by srallen** [comment]
Ah, nice catch in reading the docs. `import` seem a better fit for what we'd like to do. I'd like to rename it to be consistent with the convention here. It gives it a clear delineation between the too. The old ZRC will remain since we have at least a couple of apps that use it, but the readme should be updated that it's been deprecated and that the library is now moved and maintained here.

This is a good intro article on lerna I found: https://codeburst.io/monorepos-by-example-part-1-3a883b49047e

**Comment by mcbouslog** [comment]
My WIP is on branch `add-react-components-package`. I've got a few uncommitted changes locally that adds `react-components` to `app-project` and imports the ZooFooter to index.js, though the CSS is not right. I also commented out some code that dealt with `react-swipe`, and some "window is not defined" issues with certain components and dependencies ([related NextJS notes](https://github.com/zeit/next.js/wiki/FAQ)). I'll keep at it unless hear otherwise.

**Comment by srallen** [comment]
@mcbouslog I think it's ok as a first pass to open a PR that imports the library and updates to React 16. Then smaller subsequent PRs can fix them so they work along with Grommet 2 updates. We won't be releasing it until it works, so it doesn't have to work for the first import PR.
