### ISSUE TITLE
Simple Dropdown: type-to-complete search?

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#5130]
## Package
lib-classifier

## Is your feature request related to a problem? Please describe.
If presented with a large list of items in a dropdown, I would like to be able to type a text fragment and have that result in filtering the list of items down to those that match. This capability is available in PFE for dropdowns, but does not appear to be available for the Simple Dropdown in FEM.

## Additional Information
I am under impression that the type-to-search capability is not enabled by our codebase, but is a standard feature of dropdowns provided by the browser. Therefore, this is not a request for enhancement in our codebase, but perhaps just enabling and making use of an available optional feature.

**Comment by eatyourgreens** [comment]
No browser supports a combobox as a native widget, but there are JavaScript combobox widgets. We already use one for the text task with suggestions.

**Comment by eatyourgreens** [comment]
Relevant Grommet PR: https://github.com/grommet/grommet/pull/6079

**Comment by eatyourgreens** [comment]
WAI-ARIA design pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/

**Comment by eatyourgreens** [comment]
A codepen I made from the WAI-ARIA example. This should work in a screen reader and from the keyboard. 
https://codepen.io/eatyourgreens/full/abEQrBg

**Comment by eatyourgreens** [comment]
>No browser supports a combobox as a native widget, 

I take this back. One of the talks at State of the Browser this year reminded me that browsers support native autosuggest with [the `<datalist>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).

**Comment by eatyourgreens** [comment]
A couple of examples of type-to-complete in browsers, with custom JavaScript widgets.

Grommet Select with search in the Grommet storybook:
https://storybook.grommet.io/?path=/story/input-select-search--search

Grommet Select is what we currently use for dropdown menus. Volunteers disliked it on Engaging Crowds because the keyboard interaction is clunky. Specifically, you can't press Tab to select an answer and move to the next task. Some discussion here: https://github.com/grommet/grommet/issues/5896#issuecomment-1041288878

WAI-ARIA accessible combobox with list autocomplete here for comparison:
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/#ex_label

The WAI-ARIA example has full keyboard support, so Tab should select an option and close the menu, which would be good for us.

The Grommet Select doesn't fully implement the [combobox autocomplete pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/), so we may have to open a PR to update Grommet, similar to what I did here for previous transcriptions in the transcription task:
https://github.com/grommet/grommet/pull/6079

If we can get the same UX and styling with `<input>` and `<datalist>`, that would save us an awful lot of work, as a lot of the JS code in both these examples is reproducing what `<datalist>` does natively in browsers.

**Comment by eatyourgreens** [comment]
There's also React Aria Components, Adobe's new component library which is built to be accessible from the start. 

https://react-spectrum.adobe.com/react-aria/react-aria-components.html
