### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#54]
Comments from #52 

> In PFE, at the moment, translations are loaded in via separate API calls eg. https://github.com/zooniverse/Panoptes-Front-End/blob/eef8e357d6dea221d49adaa235c94dc79a2f149f/app/pages/project/index.jsx#L207

> I don't think you can include them in the project request. Even so, you'd still need to request them again if the end user changed the language.

> There's a redux action defined in PFE for loading translations, which might be helpful. In the new classifier, we can probably render the translation keys directly, wherever text is printed, rather than trying to copy the structure of the resource objects like PFE does (for backwards compatibility with older rendering code.)

> On the app state side, we should localise as early as possible in the implementation. Going through PFE to retrospectively localise hardcoded strings was a pain.

**Comment by eatyourgreens** [comment]
Worth noting that Scribes of the Cairo Genizah has a much cleaner implementation of Panoptes localisation, because it didn’t have to deal with legacy code.

**Comment by eatyourgreens** [comment]
We could treat translations like other resources, so something like
`Translation.get({translated_type: 'workflow', translated_id: '1234', language: 'nl})` translates to a request for `/translations?translated_type=workflow&translated_id=1234&language=nl`.

Or we could decorate translatable resources so that we can request the translation when we request the resource.
```
TranslatedProject = Translate(Project);
TranslatedProject.get('1234', {language: 'nl'});
```

The first approach is probably cleaner. Should it be up to the consuming app to request translations separately, or should it assume that translations will be included by the client when it requests a translated resource?

**Comment by srallen** [comment]
I would prefer the former since it's a separate endpoint and Panoptes resource. I'd like to the new client to reflect the API models accurately and do less assumptions about what the consumer wants. 

We could consider a decorator later at some point, but the client should have a `translations` object with a standard set of REST request functions and functional helpers as a start.

**Comment by eatyourgreens** [comment]
In terms of the front-end, translations are flat dictionaries, so where you might previously have rendered something like `{tutorial.steps[1].content}` in JSX, you'd replace that with `{tutorialTranslation.strings['steps.1.content']}`.

PFE has a helper function to convert the translation strings into nested objects, but I think all Panoptes resources have translations defined now so that's probably not necessary.

**Comment by eatyourgreens** [comment]
Here's how to get translations from Panoptes: `GET /translations?translated_type=workflow&translated_id=123&language=en`. `translated_type` can be one of `project|workflow|tutorial|field_guide|project_page`.

The resource that comes back has a property called `strings` which is a flat dictionary of language strings for the requested resource eg. the translation for `tutorial.steps[0].content` would be `tutorialTranslation.strings["steps.0.content"]`.

I think that's basically it for localising resources in the interface. Scribes of the Cairo Genizah is the only projects that has implemented this so far, I think, so that code should have practical examples.

**Comment by rogerhutchings** [comment]
We should also link the translation ID to the classification

**Comment by srallen** [comment]
We may be able to leverage GraphQL to return the workflow and the translation in one request.

**Comment by eatyourgreens** [comment]
Looking back through the comments, I don't think I listed which resources use translations so here you go:

- Project
- ProjectPage
- FieldGuide
- Workflow
- Tutorial

**Comment by rogerhutchings** [comment]
Time estimate: 6 weeks, just to make sure we've caught every string that needs localising

**Comment by eatyourgreens** [comment]
If it's helpful, It took me about two weeks to convert PFE across to using localised strings everywhere for API resources.

**Comment by eatyourgreens** [comment]
I'll also add that workflow tasks took the longest. Everything else (project, tutorials, field guide and project pages) can be done very quickly once the API calls are set up.

**Comment by eatyourgreens** [comment]
Here's an RTL example from PFE.
https://rtl.pfe-preview.zooniverse.org/projects/judaicadh/scribes-of-the-cairo-geniza/classify?env=production&language=he

Adding RTL styles was probably the smallest piece of work. [Scribes of the Cairo Geniza](https://www.scribesofthecairogeniza.org/) also supports RTL: select Arabic or Hebrew from the language picker at the top right.

**Comment by eatyourgreens** [comment]
Are there issues for localisation of the project app and the classifier? @AnLand reminded me that there are outstanding issues with UI text in PFE. https://github.com/zooniverse/Panoptes-Front-End/issues/5464#issuecomment-554637084

**Comment by srallen** [comment]
@goplayoutside3 this is an old discussion about implementing translations that may or may not have some helpful information. It's up to you to use it or close in favor of more specific implementation issues.

**Comment by AnLand** [comment]
I think those are still an issue for non-native English speakers, but sure - your decision.

**Comment by srallen** [comment]
@AnLand This is a catch all issue without specific actionable items. Closing this doesn't mean we wouldn't address the specific issue you've raised. Thanks!

**Comment by AnLand** [comment]
Thanks - complete translation of all project/website/personal account parts would help tremendously the effort of the project teams to provide the whole citizen science experience in a native language. It is hard to do and I am not sure how big the impact from non-US volunteers actually is, but for many projects it could make a big difference.

**Comment by lcjohnso** [comment]
See https://github.com/zooniverse/front-end-monorepo/projects/15 for up-to-date break-out of remaining issues and work.
