### ISSUE TITLE
Styling bug in task area

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#561]
**Package**

lib-classifier

**Feature or Issue Description**

The task area height matches that of the subject viewer, instead of matching its own content.

<img width="638" alt="Screenshot 2019-03-18 10 41 58" src="https://user-images.githubusercontent.com/2725841/54524732-9f54b300-496a-11e9-9b0e-64a8190302e9.png">

**Comment by srallen** [comment]
I'm not sure if the height is the bug. I think @beckyrother intends for the task area to be a fixed height and wants the next/done buttons to be in a fixed position as well. So the bug is that the next button isn't at the bottom.

**Comment by beckyrother** [comment]
Exactly, thanks @srallen 👍 Volunteers have complained that the buttons move around too much which creates more wrist strain during long periods of classifying. A quote that stands out to me from the user survey I did in 2017 was something like "you've created a carpal tunnel torturing device". Keeping the buttons in the same place should help a little.

**Comment by rogerhutchings** [comment]
Fair enough. In that case: 

1. Should it be aligned to the bottom of the classifier marking area, or the bottom of the classifier (inc. buttons underneath)?
1. Should we actually set the height to that of the longest question, as it will still move if there's a question longer than the classifier height? That might have to wait for a second pass, but worth flagging now.

**Comment by beckyrother** [comment]
1. It should be aligned to the bottom of the classifier marking area.
2. I'm thinking of that height as a min-height, so it can stretch longer if the question is longer. 
also worth mentioning:
3. It would be great if the question can be sticky to the top of the screen in the case of a longer subject (Notes from Nature is a great example of this), that way there's less scrolling up and down.

**Comment by srallen** [comment]
I would suggest just making it a fixed height (or having a max-height also) with overflow rather than letting it stretch as a means to encourage projects to not have workflow steps with excessively long tasks (so they can think about breaking it up into smaller workflows or smaller individual tasks). We could also enforce this in a new workflow editor to have a max allowed number of tasks per step too.

**Comment by beckyrother** [comment]
How would the overflow work?

**Comment by srallen** [comment]
When we have a fixed height or max-height set on a container, when the container overflows and we have `overflow: auto` set in the css, a scroll will be available (whether or not it is visible before you start scrolling depends on OS). Thinking more about it, perhaps this is a bad idea since it'd be possible for users to miss a task if it isn't set to be required. Maybe alternatively just enforcing a max number of tasks per steps in the lab is the only way to do it.

**Comment by beckyrother** [comment]
I think that's a good idea. Maybe we can make an exception for currently active projects, but start enforcing that rule with the launch of the new classifier. 

If needed, let's say 600px for the max-height since the average screen height is 643px.

**Comment by eatyourgreens** [comment]
If the subject viewer had its own scroll container, then the task wouldn't move when you scrolled the subject. You'd have to remember to scroll the subject, not the page, though.
