### ISSUE TITLE
Group Stats / User Stats styling adjustments

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#6153]
## A short list of the most pressing styling changes taken from our Internal Feedback doc.

Bar Chart:
1.  Selected tab (Classifications, Hours) text should be #000000, and the underline #005D69
2.  The Projects dropdown should sort alphabetically
3.  The Y axis values should be whole numbers
4.  Replace the default group logo with our Teal Zooni logo (40px)
5.  Dark Mode: When hovering over the bars, the 'detail box' needs to have an opaque background color

Mobile:
1. Collapse all buttons to the Group Options dropdown before the button text wraps to 2 lines; do not allow the text to wrap (see below)
<img width="600" alt="Screenshot 2024-07-02 at 11 52 49 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/ce9278af-05c9-4ed6-b8ee-6d7ad3a3c02c">

2. Center 'Generate Certificate' button

Group Modal:
1. Change copy in show individual stats dropdown - 'Yes, show individual stats to members'
2. Darken background when modal is opened

Question:
It looks like a recent change happened where the side-by-side panels change to full width panels, (Projects, Contributors) but they do so at around 1546 px. I do like that behavior but can we change the width to 1280px?

This also seems to have affected the homepage layout.

**Comment by goplayoutside3** [comment]
Here's an itemized list of changes I could achieve in #6197 

Bar Chart:

- [x] Selected tab (Classifications, Hours) text should be #000000, and the underline #005D69
- [x] The Projects dropdown should sort alphabetically
- [ ] The Y axis values should be whole numbers
    - Can't make this happen due to Grommet's tight control of y-axis value calculations. See Mark's comment here: https://github.com/zooniverse/front-end-monorepo/pull/6175#issuecomment-2266229678
- [x] Replace the default group logo with our Teal Zooni logo (40px)
- [ ] Dark Mode: When hovering over the bars, the 'detail box' needs to have an opaque background color
    - Also can't make this happen due to Grommet's control over tooltips in a BarChart. I searched and searched and couldn't figure out the classname of the tooltip or any way to access its styling.

Mobile:

- [x] Collapse all buttons to the Group Options dropdown before the button text wraps to 2 lines; do not allow the text to wrap
- [x] Center 'Generate Certificate' button

Group Modal:

- [x] Change copy in show individual stats dropdown - 'Yes, show individual stats to members'
- [x] Darken background when modal is opened

Question: It looks like a recent change happened where the side-by-side panels change to full width panels, (Projects, Contributors) but they do so at around 1546 px. I do like that behavior but can we change the width to 1280px?

- Yes for the homepage and My Groups page. Not for an individual Group Stats page because the entire page was built assuming a 'small' 'medium' 'large' breakpoint system, and I can't untangle the grid vs no-grid of Top Projects, order of displaying Contributors and Top Projects, and the overall layout grid of that page. I spent about 40min experimenting, but it's too late to introduce a custom breakpoint there.

**Comment by seanmiller26** [comment]
Great! I think we tackled the most important issues presented here. The pages can go live with the other minor details that couldn't be figured out at this time. Thanks for investigating those!
