### ISSUE TITLE
Incorrect timing on the stats page

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6441]
## Package
- lib-user

## Describe the bug
A weird glitch on the stats page today. I spent about 10 minutes on Squirrel Mapper, and I’ve been credited with almost 4 hours. 

<img width=400 alt="Daily stats showing 225 minutes for today." src="https://github.com/user-attachments/assets/e9045b30-66fd-4ffa-83b5-92623fccdbd4">

## To Reproduce
I’m seeing this on my personal stats for this week. 

https://www.zooniverse.org/users/eatyourgreens/stats?start_date=2024-10-30

## Expected behavior
Today’s count should show 10 minutes, maybe less.

**Comment by goplayoutside3** [comment]
The hours displayed in the personal stats page are calculated based on the start and end times of your classification efforts. For all classifications 2015 and beyond, the calculation for time spent on each classification is a straightforward subtraction: finished_at - started_at. We then add up all these values to get the number of hours you've spent classifying. 

In some cases, volunteers leave browser tabs open on a project's classify page. This means a classification's "started at" is recorded, but the "finished at" might be recorded at a much later time once the volunteer returns to that tab. We try our best to take care of idle sessions by having a session cap in place.

I'm closing this because idle sessions is the likely cause. Your classification count for Squirrel Mapper today (19 classifications) is correct. In the future if you have questions about how stats hours are recorded, please ask via contact@zooniverse.org so a backend member can do a deep dive into your user account data.

**Comment by eatyourgreens** [comment]
I did one session today, in one tab. Usually I classify on my phone, so idle tabs shouldn’t be an issue. 

Maybe a failed classification got stuck in local storage? 🤷🏻‍♂️

**Comment by goplayoutside3** [comment]
A failed classification in local storage is also a possibility, but my response about using contact@zooniverse.org to get in touch with a backend dev with questions about specific classification data is the best way to deep dive if you want to. This Issue will stay closed and unmonitored as it's too vague to be iterated on for actionable solutions.

**Comment by eatyourgreens** [comment]
That’s okay, I can pull my classifications from the API and take a look. Just thought you might like to know that the time spent sometimes has weird errors.

**Comment by eatyourgreens** [comment]
I was wrong. I started that classification at around 17:32:00 and finished it at 17:32:48. The bug is in `classification.metadata.started_at`, not `classification.metadata.finished_at`.

**Comment by eatyourgreens** [comment]
Moved this into #6447, with a fix in #6449.
