### ISSUE TITLE
Branching in the single choice task isn't supported

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#687]
**Package**

lib-classifier

**Comment by rogerhutchings** [comment]
Time estimate: 1 dev, 1 week

**Comment by srallen** [comment]
Workflow steps ADR has an example of how branching logic will be supported with workflow steps: https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-05.md#decision

**Comment by srallen** [comment]
This also can be developed against the kitteh zoo staging project as the first step/task should be a branching single choice question.

**Comment by mcbouslog** [comment]
I've created draft PRs for two of likely a few approaches:

#1747 - adds `next` property to `Step`, similar to what intended for recursive workflows as stated in https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-05.md#decision
- Note: as expected with MST/observables, TaskNavButtonsContainer doesn't rerender on a change to the active step next property, as the active step is still the same, the steps haven't changed, so why would it rerender, but I want it to rerender! [console.logging `step.next` forces a rerender](https://github.com/zooniverse/front-end-monorepo/pull/1747/files#diff-491dac2863aa29086de04a585966846fR80), but that's not proper

#1748 - adds `next` to `workflowStepStore`

Going Back/Previous breaks either at the moment.

In this test workflow - https://master.pfe-preview.zooniverse.org/lab/1693/workflows/3428, it should go:
single q (0, 1, 2)
 0 - complete
 1 - drawing, then complete
 2 - text, then complete
However, after the drawing task it advances to the text task, because the workflow step store does not currently account for the next task setting (on any task, including the branching of the single question task). Is this what we refer to as a recursive workflows, and is therefor out of scope of this issue? That's fine, I can just focus on advancing from a single choice question, but they're (single choice branching, any task next's setting, going back/previous) so interrelated I'm not sure if should be considered at same time?

**Comment by srallen** [comment]
After discussing this with @mcbouslog, we've realized that once a branching has occurred, we will always need to explicitly know what step is next and previous. Say a branching workflow looks like this:

|Step A|
|           |
|           |
[B]       [C]
|           |
[D]      [E]

And the step map looks like this:
[[A],[B],[C],[D],[E]]

We can't rely on the map order once the branching happens.

So, we need to tweak how this works and define a `next` and `previous` for all steps:

- by the action that converts tasks to steps
- or assuming the editor correctly sets this for steps like it does for tasks now and so the snapshot from the resource is correct from the start. The default can be the map order, but can be modified if set for branching or recursion.
- or updated by action when a single choice answer with branching is chosen (for next)

How to determine the previous step with branching still needs some thought.

We'll need to write up an updated ADR for these changes.
