### ISSUE TITLE
Staged branch deploys for PR reviews

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#694]
**Package** app-project, lib-classifier?

**Feature or Issue Description**
It would be useful for PR review especially for the design review process (noted in #666)

**Comment by rogerhutchings** [comment]
I've got an idea for how this could work:

1. A PR gets created on GitHub
1. Jenkins picks up the PR, builds a staging docker image which starts up all the apps, and a small proxy for handling routing
1. Image gets deployed to a new kubernetes pod, which runs it all
1. Jenkins comments on the original PR with the staging branch address
1. When the PR is closed, the pod is trashed

Questions / Things to do:

- Write a dockerfile (which can be based on https://github.com/zooniverse/front-end-monorepo/blob/master/Dockerfile) which builds the libraries and apps, starts them up, and starts a proxy with some routing rules
- Do kubernetes pods have individual IPs which we could use instead of having to automate changes to the web ingress, or is there another way we could access them?
- Would totally automating the process be a security concern? On reading this back, I think it could certainly be open to abuse, so we could configure lita to do it, or write a GitHub bot to do it via comments

**Comment by adammcmaster** [comment]
I think we can get this working roughly how you've described. Two things I think we'll need to look into:

1. I'm not sure how easy or hard it might be to get Jenkins to comment on a PR. 
2. I'm also not sure offhand how to get Jenkins to delete the pod when the PR is closed.

I suspect both of those will be possible though.

> Do kubernetes pods have individual IPs which we could use instead of having to automate changes to the web ingress, or is there another way we could access them?

I think we could just add a wildcard domain (similar to how we have `*.preview.zooniverse.org` now) and add that to the ingress, proxying to Nginx or something that can translate the hostname to the internal Kubernetes service name (which can just be a prefix followed by the branch name). Maybe the Kubernetes ingress can do that without even needing Nginx.

> Would totally automating the process be a security concern? On reading this back, I think it could certainly be open to abuse, so we could configure lita to do it, or write a GitHub bot to do it via comments

I think that'll be fine. Jenkins will only execute on PRs from people who have write access to the repo so that will prevent any random person from abusing it.

**Comment by srallen** [comment]
Named stages aren't supported by the Jenkin's Docker plugin: https://github.com/jenkinsci/docker-workflow-plugin/pull/162

There's an open pull request to solve this: https://github.com/jenkinsci/docker-workflow-plugin/pull/180

What I suggest we do going forward is to not use this feature now and keep a watch on the open PR. If it is accepted, we can give it another try.

**Comment by eatyourgreens** [comment]
https://github.com/jenkinsci/docker-workflow-plugin/pull/180 has been merged, so that's a good sign.

**Comment by srallen** [comment]
TODO:

- [ ] Setup a staging sub-domain

 Option A
- [ ] Setup a single kubernetes pod that runs all the apps and a proxy to this sub-domain

Options B
- [ ] Setup a new kubernetes instance with a pod for each app
- [ ] Setup a cloudfront instance for the URL for routing
   - [ ] Add routing rules for staging vs production

What are the trade offs?
Option A:
-  + Less dev time
-  - Not the same as the production environment

Option B:
- - More dev time
- + Same as production environment

**Comment by camallen** [comment]
Is the trade off in Option B a one off cost to get deployments in place / domains / routes setup etc? If so i think it's worth the investment in time. 

Also it is worth mirroring the production setup as close as possible. Having a place to test cloudfront rules and app interactions is critical and currently we do that on production.

**Comment by rogerhutchings** [comment]
It is, yes - not just our time, but yours / Adam's / Zach's etc.

Just for the sake of completeness, it's just occurred to me that to do a true like-for-like deployment, should we be deploying the master branch to our staging instance first and _then_ the feature branch, just to catch any caching issues etc?

**Comment by camallen** [comment]
> It is, yes - not just our time, but yours / Adam's / Zach's etc.

This is worth our time

**Comment by srallen** [comment]
Based on our discussion, we should mirror production as much as possible. 

Option A:
- Can kubernetes handle deployment to subdomains setup?
  - Ideally we want a wildcard entry in the ingress config. We need to check if this is supported.
  - If it is not supported, we can run a third load balancer?
  - After a quick look, wildcards are not supported. 

Option B:
- Can we instead switch master deployments to staging and manually deploy production using a git tag?
  - Jenkins would check the git tag to determine where the deployment goes
  - Branch deployments could be "manual" if needed for design review triggered by script (lita, github bot) etc that then can be teared down after merged
   - Helm could be leveraged to tear down pods(namespaces?) using the branch name

We've decided to go to Option B. An ADR will be written to reflect this decision.

**Comment by eatyourgreens** [comment]
Jenkins docker plugin was fixed two weeks ago. Can we upgrade Jenkins to the latest version, which should fix the bug when parsing `FROM imageName AS targetName`.

**Comment by srallen** [comment]
We have a staging instance for deploys from master upon merging now. We still need to write a script for a temporary deployment for branches as agreed to in ADR 17
