### ISSUE TITLE
Add cursor key support for panning in LCV

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#722]
**Package**

lib-classifier 

**Feature or Issue Description**

We should allow cursor keys to pan horizontally in the light curve viewer, as PFE does

**Comment by eatyourgreens** [comment]
+/- keys to zoom would be good too. PFE listens to them when the subject has focus, so you can zoom and pan with the keyboard while also drawing with the mouse. Here's a working example: https://www.zooniverse.org/projects/penguintom79/seabirdwatch/classify

**Comment by eatyourgreens** [comment]
See #727 for keyboard support.

**Comment by eatyourgreens** [comment]
Re-opening this. It's partially fixed by #727 and #729 but the light curve viewer still needs to be updated to be focused when you're drawing. At the moment, focus goes to the document body when you mark a transit, so keyboard events aren't captured by the viewer. [Managing focus in SVG](https://allyjs.io/tutorials/focusing-in-svg.html) has useful advice. Cross-browser support for keyboard focus in SVG might involve adding `focusable` (IE and Edge) and `tabindex`(Firefox and Chrome)  to SVG elements: `<g focusable=true tabindex=0 />`.
