### ISSUE TITLE
Should we make annotation value types consistently iterables?

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#823]
**Package** lib-classifier

**Feature or Issue Description**
The variability of type of the annotation value has been a consistent source of issues and pain for the aggregation service and possibly other post-classification services. For example, this recent PR was to account for the possibility of the annotation value either being an array, object, number, or string: https://github.com/zooniverse/aggregation-for-caesar/pull/154

I'd like to propose that we always make the annotation value an array with the annotation values contained therein. So, the change I see for the following tasks are:

- Single choice: `value: 0` to `value: [0]`
- Multiple choice: already an array of numbers
- Drawing: already an array of objects
- Crop: `value: {}` to `value: [{}]`
- Text: `value: ""` to `value: [""]`
- Survey: already an array of objects
- Dropdown: already an array of object
- Slider: `value: 3` to `value: [3]`
- Highlighter: already an array of objects

In addition to this, I'm also thinking about adding a `taskType` which would be a string of the type like single, multiple, survey, etc so the type is explicitly sent in along with the annotation value rather than rely on type checking to try to figure out what the annotation task type was. For example:

```
{
  task: 'T1',
  value: [0],
  taskType: 'single'
}
```

Any reason this is a bad idea? cc @camallen @zwolf @CKrawczyk

**Comment by eatyourgreens** [comment]
In https://github.com/zooniverse/Panoptes-Front-End/issues/4478 we considered adding a schema for annotations. So you'd publish a task with a URL that describes the annotations. Classifications would include that URL, so that Caesar etc. can look it up and find out what format annotations should be in.

If the task is changed/updated it should publish a new schema, then any new classifications use the updated schema URL and aggregation knows the format has changed.

It might be too heavy-handed of an approach, but it would allow us to do things like change the data format for freehand tasks, without breaking aggregation code that needs to be backwards compatible with old classifications.

Otherwise, I think we're locked into a single annotation type for each task type, because all annotations for that type re expected to be in that format.

**Comment by CKrawczyk** [comment]
I like the idea of passing along the `taskType` inside the classification, that could make things like auto-configuration easier and reducer the need for checking data types when multiple task types share an extractor (e.g. https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/extractors/question_extractor.py#L56-L60).

That should be more than enough information for the aggregation code to know what data shape to expect, I don't really think forcing everything into an array is needed.

**Comment by eatyourgreens** [comment]
I suppose switching to an array could lead to potential bugs like a single answer task submitting something like `[1, 2]` as the value.

**Comment by srallen** [comment]
Ok, so it sounds like adding `taskType` is useful and immediately doable by us. Long term, a definition hosted somewhere and linked in the classification of each type would be useful, especially for versioning purposes.
