### ISSUE TITLE
LCV: Feedback doesn't always render all of the json points

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#851]
**Package** lib-classifier

**Feature or Issue Description**
>  it looks like it just didn’t load properly because the LC shouldn’t finish at 18 days? And the data points look like they’ve been cut-off.

> I’ve been able to reproduce this, on the very first subject I got. I marked a transit at ~20 days to see what would happen.

![Screen Shot 2019-05-17 at 11 42 03 AM](https://user-images.githubusercontent.com/5016731/58045525-5c4cc280-7b08-11e9-944d-cea4d372e457.png)

![image](https://user-images.githubusercontent.com/5016731/58045538-62db3a00-7b08-11e9-8252-f50aec6f773d.png)

**Comment by mcbouslog** [comment]
This is related to Grommet Box `height` and `width` settings. 

The data svg circle elements are in the dom, but I can't figure out why they're not showing. Setting the FeedbackViewer's parent Box, or it's grandparent Box, to a height or width of `large` or similar appears to cause the issue.

I'll open a PR setting the FeedbackViewer's parent Box to 400px for now.

**Comment by shaunanoordin** [comment]
## Investigation Results

### Problem
- When a LightCurveViewer component is shown in a Feedback modal, some of its data points are "cut off", despite existing in the DOM.

![Screen Shot 2019-05-22 at 18 07 50](https://user-images.githubusercontent.com/13952701/58194330-200e9300-7cbd-11e9-92dd-20b0c26776c7.png)
_Light Curve Viewer showing data normally. Clicking on the 'Done' button shows the Feedback modal, which we see in the next screenshot._

![Screen Shot 2019-05-22 at 18 09 03](https://user-images.githubusercontent.com/13952701/58194348-2d2b8200-7cbd-11e9-9a62-2f118953858b.png)
_Light Curve Viewer in a Feedback modal, with several points of data missing or clipped off._

### Diagnosis

- This is due to two factors:
  - each LCV has a `<clipPath id="data-mask">` element, which is a visibility mask that limits where the data points in `<g class="data-layer" clip-path="url(#data-mask)">` can be seen.
  - the Feedback modal is creating a second LightCurveViewer component
- The second LCV (in the Feedback modal) is confused as to which `#data-mask` it's supposed to use to clip its visible data points. (Data masks are defined by DOM id, which is just a string)

![Screen Shot 2019-05-22 at 18 08 14](https://user-images.githubusercontent.com/13952701/58194614-edb16580-7cbd-11e9-8d1b-0be464d49c75.png)
_The `#data-mask` of the first LCV. Note its small squareness._

![Screen Shot 2019-05-22 at 18 09 18](https://user-images.githubusercontent.com/13952701/58194633-face5480-7cbd-11e9-8666-f8ece5b50db0.png)
_Note how the second LCV has its data points cut off to roughly the same size and shape of the first LCV's small square `#data-mask`_

### Solution
- Simplest solution is for every LCV to create a unique ID for its data mask, e.g. `<clipPath id="data-mask-133769">` and `<g class="data-layer" clip-path="url(#data-mask-133769)">`

**Comment by eatyourgreens** [comment]
Just noting that duplicate IDs are invalid HTML. I think the browser will always select the first element with a given ID, because IDs are expected to be unique.
