### ISSUE TITLE
'Done and Talk' bug

### ISSUE THREAD

**Issue by trouille** [zooniverse/front-end-monorepo#900]
**Package**

**Feature or Issue Description**

https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2108/1020172?comment=1682439&page=1 provides thread. In brief, 'Done and Talk' works for sims, but not for regular subjects. As Jim noted in the #tess slack thread, "Sounds like going to Talk fails unless there’s feedback, which points to a bug in the action code."

**To Dos**

- [ ] Example

**Comment by eatyourgreens** [comment]
I _think_ this is happening because Done & Talk sets a callback that only gets called for subjects with feedback.
https://github.com/zooniverse/front-end-monorepo/blob/dc18211d7782029454fd006dde22556d2af8bfeb/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.js#L69
