### ISSUE TITLE
Message that IE 11 is not supported

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#906]
**Package** app-project

**Feature or Issue Description**
Message instead of just showing a broken app

**Comment by eatyourgreens** [comment]
Add older versions of Safari to this list too. Could we do feature detection to find old browsers?

I'd suggest having this for the classifier, rather than the project app, since the app uses SSR and should, in theory, not depend on browser versions.

**Comment by srallen** [comment]
We should have fallback messages for both because both can have issues for different reasons. In the project app, we're using modern CSS, like grid, that old browsers don't support either.

**Comment by eatyourgreens** [comment]
We could add a message to the page template that's styled to `display: none` with a selector that those browsers don't support.

**Comment by lcjohnso** [comment]
+1 on enabling this message for IE11 users -- 1 contact ticket received for PH TESS project.

**Comment by srallen** [comment]
CSS supports API: https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports

**Comment by wgranger** [comment]
Do we have a design of what this message should look like?

**Comment by srallen** [comment]
We don't, but I don't think this needs much design time. It can just be a paragraph with a text like:
```
Your web browser is no longer supported by the Zooniverse. Please update your browser.
```

Or we could use something like this? https://browser-update.org/

Not sure if anyone has objections to it.

**Comment by wgranger** [comment]
I think our use of browser-update depends on what our aim is. Do we want to display items like the header and footer with a body message that says "update your browser," or do we want to display nothing at all except a message that says "update your browser?"

**Comment by srallen** [comment]
In the case of IE, we don't really want to display broken elements. I don't think we're using CSS Grid in the header and footer, but I'm not totally sure on that.

**Comment by wgranger** [comment]
I'm not positive I'll be able to close this before starting text editor work since this is proving to be a bit trickier than I thought. Initially, I thought I could detect the browser on `componentDidMount`, when the `window` object would be available (due to client-side rendering) but IE never gets to that point because the browser gets hung up on some ES6 syntax during the initial render. However, you should be able to detect the browser by injecting a script into the head and proceed from there. So, my suggestion is one of the two:

1) Polyfill for ES6 in IE using a method similar to [this](https://github.com/zeit/next.js/issues/2060) and detect the browser on `componentDidMount`. I've tried doing this and it has proved a bit tricky, possibly due to how our package.json is set up with multiple apps in one repo.
2) Detect the browser through a header script and respond accordingly with an alert message or try using browser-update.
